### ISSUE TITLE
Is it possible to use texture on solid-line road?

### ISSUE THREAD

**Issue by native1989** [heremaps/harp.gl#1057]
Your library looks great and provide opportunity to create realistic 3d maps. But for render-like images it will be cool to draw texture pattern on roads
<img width="400" alt="Screen Shot 2019-11-21 at 11 56 10" src="https://user-images.githubusercontent.com/807140/69314579-53bf7b00-0c56-11ea-8f22-1a632f6ecd91.png">

**Comment by skosmella** [comment]
@native1989, unfortunately adding textures on solid lines is currently not supported. But we will consider your feature request and add it to our backlog.

**Comment by kkostecki** [comment]
Hello @native1989 !
We are happy hear that harp.gl reaches such a broad spectrum of usage, although current implementation of roads rendering is focused on merely on performance. 
This implies certain limitations, thus our roads do not even have full geometry defined in pre-processing phase, they are simple poly-lines, which are converted/extruded to real polygons in a vertex shader.
The problem with real textures lays in correct stitches on the junctions, curves, etc. If we don't know the actual texture (for example were the lane stripes are) we may not provide correct stitching, but stay tuned we will consider it in the incoming features set!
