### ISSUE TITLE
Support mixed level of detail (LOD)

### ISSUE THREAD

**Issue by ninok** [heremaps/harp.gl#1061]
**Is your feature request related to a problem? Please describe.**
Currently the whole view is filled with tiles coming from the same data-level. This leads to a lot of tiny tiles rendered at the horizon with a bad impact in performance. This also forces us to keep the horizon quite close to the camera.

**Describe the solution you'd like**
It should be possible to mix tiles from different data-levels in one view so that the size of the tiles on the screen are more or less equal.

**Comment by skosmella** [comment]
Mixed LOD has been implemented and is now available as an option. The feature is not enabled by default.
We currently still see a limitation around the poles when tiles of different LOD-level converging. Issue is being addressed internally.
