### ISSUE TITLE
Rendering of mapAnchors' objects "inside" 3d buildings

### ISSUE THREAD

**Issue by gizm0bill** [heremaps/harp.gl#1066]
I'm trying to make custom added objects visible behind or when intersecting the 3d buildings meshes. Now I know they are not transparent but I don't understand how are the other map features visible behind them and custom objects not. Can anyone point me in the right direction on how to achieve this:
![Annotation 2019-11-21 181518](https://user-images.githubusercontent.com/189533/69355717-f09c0b80-0c8a-11ea-9f58-3c3e299f883f.png)

**Comment by nzjony** [comment]
The buildings are transparent, so you need to make the cube material's flag transparent to true, and then keep the opacity to 1. You will also need to ensure the renderOrder is correct of the mesh. Check the style file to see what renderOrder the buildings are given.

the roads are visible behind because they are forced to be transparent.

**Comment by gizm0bill** [comment]
I have tried this but with no success:
<img width="808" alt="Screen Shot 2019-11-21 at 9 45 18 PM" src="https://user-images.githubusercontent.com/189533/69371319-4d59ef00-0ca8-11ea-87e7-92e22e3d1947.png">

(also, after debugging I found out that the buildings material - ExtrusionFeatureMixin - is not transparent, i.e. the property is set to false)

**Comment by gizm0bill** [comment]
Investigating more, found out it has something to do with the `DepthPrePass` thing

**Comment by nzjony** [comment]
@gizm0bill, yes, good spotting, that looks like it is the issue, see: https://github.com/heremaps/harp.gl/blob/f28f129bbbfffca1c17d26751e80e3171b9a7d3b/%40here/harp-datasource-protocol/lib/TechniqueParams.ts#L1094

Sorry I led you down the wrong path, I'm not so familiar with this code.

It seems that all objects rendered with the ExtrudedPolygonTechnique with opacity < 1 are rendered as a depth prepass.

In that case, to have the box render beneath the buildings, you would need to disable the depth test. Some of the devs are on: https://app.slack.com/client/T9JGBQ09Z/CK47C5NFN so you can try contacting us here if you want to ask us some more questions and get a more real time response.

**Comment by ninok** [comment]
Hi @gizm0bill,

thanks for reporting this issue. You are right , with the depth-pre-pass it is not possible to render anything behind the buildings.
A typical trick to get the behavior you want is to render the object twice:
1. first pass without depth test either
* as @nzjony mentioned with a semi-transparent material or
* with an opaque material before the building pre-pass
2. second pass with depth test and full opacity to get the part that is not behind a building.

**Comment by gizm0bill** [comment]
Thank you for the tip @ninok ! 
You wouldn't happen to have an example piece of code for this by any chance? I'm still pretty noobish at this

**Comment by ninok** [comment]
I added the two pass rendering to our example:
https://github.com/heremaps/harp.gl/pull/1075

**Comment by gizm0bill** [comment]
Thank you! Much appreciated!

**Comment by nzjony** [comment]
@gizm0bill , can I close this issue now that we have the example? Or do you want anything else in particular?

**Comment by gizm0bill** [comment]
Yes you can close it. I do have some more questions but I'm going to ask them over slack if I may, thanks!
