### ISSUE TITLE
Time dynamic data?

### ISSUE THREAD

**Issue by jfuehner** [heremaps/harp.gl#1164]
Hi! I am currently using Cesium on a project but have been running into some limitations when trying to visualize large quantities of polygons over time. Harp has peaked my interest as it *appears* it may be able to handle such a use-case.

With that said, I was curious if harp supports a similar concept to Cesium's time-dynamic functionality. 

https://cesium.com/blog/2018/03/21/czml-time-animation/

If not, would you have a recommendation on how this may be accomplished using harp?

Thanks!

**Comment by ninok** [comment]
Hi Jason,

have you checked our example that shows the history of the European Union:
https://www.harp.gl/docs/master/examples/#datasource_features_polygons.html

Documentation is here:
https://www.harp.gl/docs/master/doc/modules/harp_examples.polygonsfeaturesexample.html

The code is here:
https://github.com/heremaps/harp.gl/blob/master/%40here/harp-examples/src/datasource_features_polygons.ts

What it basically does is creating a datasource per timestep.

Is this what your are looking for? Happy to hear your opinion.
