### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by songsgroup** [heremaps/harp.gl#1170]
**Describe the bug**
 
![Video_2019-12-25_100242](https://user-images.githubusercontent.com/9037515/71428884-a0d3b880-26fe-11ea-9794-04d1871a6cfe.gif)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by skosmella** [comment]
Thanks @songsgroup for reporting this issue. 
We do already have a corresponding ticket in our backlog and working on a fix by introducing mixed LOD functionality.  
Please also refer to https://github.com/heremaps/harp.gl/issues/1061

We hope to provide a proper solution within the next couple of weeks. Please stay tuned.

**Comment by kkostecki** [comment]
@songsgroup bug fixed, with #1061, although we are still working on some improvements for mixed LOD, please leave a note if you are satisfied with current solution.

**Comment by nzjony** [comment]
@songsgroup , @kkostecki , I'll close this, as it seems to be fixed, please re-open if there are any further concerns.
