### ISSUE TITLE
Support terrain

### ISSUE THREAD

**Issue by songsgroup** [heremaps/harp.gl#1171]
Is your feature request related to a problem? Please describe.
Support terrain

**Comment by musculman** [comment]
Hi @songsgroup and thank you for opening a feature request for harp.gl!
May I ask for clarification? What kind of terrain would you like to see supported? Are you referring to something like https://github.com/heremaps/harp-terrain-datasource ?

**Comment by nzjony** [comment]
@songsgroup , check out: https://github.com/Astrak/harpbox

**Comment by Astrak** [comment]
Is it possible to provide some input in this issue about the terrain feature? It would be nice to know about the development status (planned/in progress), and if the data will be available publicly (also, what kind of data if it's not too sensitive :innocent: (TIN?))
