### ISSUE TITLE
Is it possible to have the road labels be rendered underneath an object placed on the map? 

### ISSUE THREAD

**Issue by nigelkp9** [heremaps/harp.gl#1310]
Currently I have a map with various objects anchored to the map, but the issue I'm having is that road labels and other related stuff are being rendered on top of my objects, I want them to be rendered under my objects. Is there a way to do this, or would I have to render my objects onto a separate canvas?

**Comment by nzjony** [comment]
@nigelkp9 , thanks for your issue. Are these objects 3D or 2D objects? Currently there isn't a way to put 3D objects on top of the text, you can see this in `MapView` that we have first the call to ` this.mapRenderingManager.render` which renders the scene, then a few lines later we have a call to `finishRenderTextElements` which renders the text. 

We support user text / poi elements with the `addOverlayText` api on the `MapView`. But not yet with 3D.

If you have 3D objects, what you could do is have a separate threejs scene and render it after the map has completed, you could do it like this:

```
        const mycustomescene = new Scene...
        const renderCustomThreeJSScene = () => {
            mapView.renderer.clearDepth();
            mapView.renderer.render(mycustomescene, mapView.camera);
        };
        mapView.addEventListener(MapViewEventNames.AfterRender, renderCustomThreeJSScene);
```

Does that help?

**Comment by nigelkp9** [comment]
> @nigelkp9 , thanks for your issue. Are these objects 3D or 2D objects? Currently there isn't a way to put 3D objects on top of the text, you can see this in `MapView` that we have first the call to ` this.mapRenderingManager.render` which renders the scene, then a few lines later we have a call to `finishRenderTextElements` which renders the text.
> 
> We support user text / poi elements with the `addOverlayText` api on the `MapView`. But not yet with 3D.
> 
> If you have 3D objects, what you could do is have a separate threejs scene and render it after the map has completed, you could do it like this:
> 
> ```
>         const mycustomescene = new Scene...
>         const renderCustomThreeJSScene = () => {
>             mapView.renderer.clearDepth();
>             mapView.renderer.render(mycustomescene, mapView.camera);
>         };
>         mapView.addEventListener(MapViewEventNames.AfterRender, renderCustomThreeJSScene);
> ```
> 
> Does that help?

Yes, they are 3D objects. Thank you, I figured I'd have to do something like

**Comment by nzjony** [comment]
@nigelkp9, I will close this, please reopen if you have any further questions.
