### ISSUE TITLE
What is the correct way to manage situations where a datasource fails to connect? 

### ISSUE THREAD

**Issue by nigelkp9** [heremaps/harp.gl#1347]
Under poor network conditions attempting to add a datasource often results in the following error being returned

`Failed to connect to datasource anonymous-datasource#x: Timeout exceeded when waiting for first message from worker`

I would assume that removing the bad datasource and trying to add another would be the way to continue, but every time I've caused the above error to happen, every following attempt to add another datasource to replace the bad one instantly fails with the same message. 

To be more exact in what I did, I used the DataSourceConnect event to tell when the error occurred and removed the bad datasource using MapView.removeDataSource(), then created a new OmvDataSource and added it using MapView.addDataSource()

I though maybe there is some kind of worker that needs to be reset when this happens, but I couldn't find anything relevant in the documentation. Any help would be appreciated, thanks

**Comment by nzjony** [comment]
thanks for the bug @nigelkp9, we'll take a look.

**Comment by nzjony** [comment]
@nigelkp9 , I took a bit of a look internally, it seems that once a WebWorker fails, it stays in a failed state, and adding new DataSources as you mentioned will fail. I'm not sure if we currently have any mechanism to retry creating failed WebWorkers, I have asked internally in our team chat to see if anyone can comment directly.

**Comment by zbigg** [comment]
`harp.gl` shares `WebWorker` instances between datasources, it's not "bad datasource", but bad `ConcurrentWorkerSet` instance that we fail to heal -> this is bug.

Not yet tested, but [`ConcurrentDecoderFacade.destroy`](https://www.harp.gl/docs/master/doc/classes/harp_mapview.concurrentdecoderfacade.html#destroy)( should do the trick and ensure that we will attempt to create new workers on next attempt to create `OmvDataSource`.

**Comment by nigelkp9** [comment]
> `harp.gl` shares `WebWorker` instances between datasources, it's not "bad datasource", but bad `ConcurrentWorkerSet` instance that we fail to heal -> this is bug.
> 
> Not yet tested, but [`ConcurrentDecoderFacade.destroy`](https://www.harp.gl/docs/master/doc/classes/harp_mapview.concurrentdecoderfacade.html#destroy) should do the trick and ensure that we will attempt to create new workers on next attempt to create `OmvDataSource`.

This worked. Thank you for the timely responses
