### ISSUE TITLE
How are mapAnchors positioned?

### ISSUE THREAD

**Issue by HHammerite** [heremaps/harp.gl#1369]
I have a question about the mapAnchor node, specifically how are they positioned? I have positioned a building on the map using the .geoPosition property and wanted to set it as the target for an orbit camera. However, I am facing an issue where getting it's position is not at the visible location of the building. I added a box helper to visualise the boundaries and in-fact the helper is showing me another location up in the sky. I feel like I am doing something wrong here.

![Inkedharp-issue_LI](https://user-images.githubusercontent.com/10602138/76400942-cd0be680-6389-11ea-8fbc-9ace48de8565.jpg)

Here on the left you can see the building positioned on the map. And on the right you can see the box helper set to encapsulate the building.

**Comment by HHammerite** [comment]
Here is another screenshot where I don't set the .geoPosition of the building after it's loaded.
![harp-issue-2](https://user-images.githubusercontent.com/10602138/76401437-8c609d00-638a-11ea-8035-f941f71b8c72.png)

**Comment by nzjony** [comment]
@HHammerite , thanks for your bug report.

How are you adding the object to the `mapAnchors` ?

Setting the `geoPosition` should work, see the `render` method in `MapView`, specifically the line: 
`this.m_mapAnchors.children.forEach((childObject: MapAnchor) => {`

We position all of the children relative to the camera. This is how all objects are rendered, the camera is then located at 0,0,0 and all objects are rendered relative to it.

However we don't position the `mapAnchors` object, its position would be at 0,0,0 in world space, so for example, if you are using globe projection, then the `mapAnchors` object would be position in the center of the world, but the children are positioned correctly.

Does that help?

**Comment by HHammerite** [comment]
Hi @nzjony,

Thank you for your reply! I am adding the object to mapAnchors like this 
`map.mapAnchors.add(scene);` where map is the mapView instance and scene is the main gltf scene.

That's good that the mapAnchors object is positioned at 0, 0, 0. This simplifies a lot. 

I am adding the box helper like this
 `const box = new THREE.BoxHelper(scene);
mapView.scene.add( box );`

Is there a reason the box would be positioned like this?

**Comment by nzjony** [comment]
> I am adding the box helper like this
> `const box = new THREE.BoxHelper(scene); map.scene.add( box );`

I think I see the problem, because the scene is positioned relative to the camera, its position is updated each from, you need to add an event listener to the map render call and update the box, something like:

`map.addEventListener(MapViewEventNames.Render, () => {
    box.update();
 }`

Does that help?

**Comment by HHammerite** [comment]
That has solved half of my problem! It is now correct. Thank you @nzjony! I just need to figure out the camera issue now.

**Comment by nzjony** [comment]
@HHammerite , great to hear!

What camera issue are you dealing with, we have an orbiting camera example here if it helps: https://www.harp.gl/docs/master/examples/#getting-started_orbiting-view.html

**Comment by HHammerite** [comment]
@nzjony I've been using this [Orbit Camera ](https://www.npmjs.com/package/camera-controls). However I'm struggling to set it's orbit position to the MapAnchor. If I using the regular orbit camera from three it works without any issues, just that the orbit axis is wrong.

**Comment by HHammerite** [comment]
The reason I'm using this is because I need to set the camera's focus to specific parts of the building

**Comment by nzjony** [comment]
@HHammerite, can you try updating the target each frame, i.e. under the `box.update();`, make a call to set the target on the orbit controls?

**Comment by HHammerite** [comment]
That works! Awesome @nzjony! Thanks for your help. I have to ask for future reference, is there a way to get around all this continuous assignment & updating to simply interact with a MapAnchor?

**Comment by nzjony** [comment]
@HHammerite , I agree that it is a bit cumbersome, i will create a separate ticket to improve the interface, as you say, it should be possible to just assign objects to the MapAnchor and not have to worry about updating their positions.

**Comment by HHammerite** [comment]
@nzjony Thank you! What's the best way to keep updated on this?

**Comment by nzjony** [comment]
I created an issue: #1371

**Comment by nzjony** [comment]
@HHammerite, otherwise can I close this issue?

**Comment by HHammerite** [comment]
Cool, thank you @nzjony
