### ISSUE TITLE
[question] HTTP 401 error when following the examples and guides

### ISSUE THREAD

**Issue by trusktr** [heremaps/harp.gl#1383]
I'm fairly certain I'm following the examples correctly, but I get 401 errors so tiles don't load.

This is my code:

```js
    // import OmvTileDecoderService inside a web Worker with vanilla JS, thanks to
    // the JSPM ES Module CDN (https://jspm.io).
    const workerCode = `
        async function main() {
            const { OmvTileDecoderService } = (
                await import('https://dev.jspm.io/@here/harp-omv-datasource/index-worker')
            ).default

            OmvTileDecoderService.start()
        }

        main()
    `;
    const blob = new Blob([workerCode], { type: "application/javascript" });
    // const worker = new Worker(URL.createObjectURL(blob), { type: "module" });

    const canvas = document.getElementById("harpCanvas");
    const map = new MapView({
        canvas,

        // theme:
        //     "https://unpkg.com/@here/harp-map-theme@latest/resources/berlin_tilezen_night_reduced.json",
        theme:
            "https://unpkg.com/@here/harp-map-theme@0.13.0/resources/berlin_tilezen_base.json",

        decoderUrl: URL.createObjectURL(blob),

        //For tile cache optimization:
        maxVisibleDataSourceTiles: 40,
        tileCacheSize: 100
    });

    map.setCameraGeolocationAndZoom(
        new GeoCoordinates(1.278676, 103.850216),
        16
    );

    const mapControls = new MapControls(map);
    const ui = new MapControlsUI(mapControls);
    canvas.parentElement.appendChild(ui.domElement);

    mapControls.maxPitchAngle = 90;
    // mapControls.setRotation(6.3, 50);
    // mapControls.camera.rotation

    map.resize(window.innerWidth, window.innerHeight);
    window.onresize = () => map.resize(window.innerWidth, window.innerHeight);

    const omvDataSource = new OmvDataSource({
        baseUrl: "https://xyz.api.here.com/tiles/herebase.02",
        apiFormat: APIFormat.XYZOMV,
        styleSetName: "tilezen",
        authenticationCode: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    });

    map.addDataSource(omvDataSource);
```

where `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX` is my API key that I created by first making a new JavaScript App ID, then for that app making an API key and pasting that key in my Harp example.

Any ideas why?

**Comment by trusktr** [comment]
I also just tried to make a REST app ID, then an API key for that, but no luck. For example:

```
GET https://xyz.api.here.com/tiles/herebase.02/14/12919/8134/omv?access_token=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX 401
```

**Comment by trusktr** [comment]
Okay, looks like I actually need to go to [HERE Studio Token Manager](https://xyz.api.here.com/token-ui), not the regular Here app and api key manager, which can be confusing.

However, I've no idea how to generate a token. When I try, it says

```
No rights are selected for the token generation!
```

which isn't helpful.

**Comment by trusktr** [comment]
I'm stuck here with no idea how to make a token to try the lib. Surely this is an annoying user experience for people who've tried what I'm trying. Don't take it personally, it's just that after spending the time to [get Harp without Webpack](https://github.com/heremaps/harp.gl/issues/1382), now I can't actually run the code for reasons unknown and not related to the code).

**Comment by trusktr** [comment]
Okay, that UI is not intuitive. One needs to select check boxes in the table (which is seemingly unrelated to the pop form, and a bad UX because it is completely not obvious, those checkmarks seem more like for managing entries in the table, and there are no entries to begin with).

Anyways, now I selected some check marks, and when I click the final `Generate Toekn` button in the popup window, the JS console greets me with a cryptic

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at generateToken (tokenmatrixui.html:1277)
    at HTMLElement.onclick (tokenmatrixui.html:268)
```

:finnadie:

**Comment by nzjony** [comment]
@trusktr , thanks for your bug report, and I apologize for your frustration.

We just recently changed away from xyz to the vector tile service, see: ae5f1913d57ad2c4df139247187454af74411bdc

How did you generate the key, I guess you used this guide: https://github.com/heremaps/harp.gl/blob/master/docs/GettingStartedGuide.md#-here-credentials ?

If you change your baseUrl to the vector tile service, with the original key, does it work? See: https://github.com/heremaps/harp.gl/blob/master/docs/GettingStartedGuide.md#attach-data-source

Again sorry about this and thanks for your involvement!

**Comment by trusktr** [comment]
Hello Jonathan, thanks for the help. I tried setting `baseUrl` to `https://vector.hereapi.com/v2/vectortiles/base/mc`, then I get the errors

```
GET https://vector.hereapi.com/v2/vectortiles/base/mc/14/12919/8133/omv?access_token=XXXXXXXXXXXXXXXXXXXXXX 401
```

with `XXXXXXXXXXXXXXXXXXXXXX` being the api key.

For reference, this is the page where that key came from,

![here-project-details-javascript-api-key](https://user-images.githubusercontent.com/297678/76818327-92a7ac80-67c2-11ea-96a5-fc941869fe28.png).

**Comment by trusktr** [comment]
Ok! It worked. It needed to be this (which ironically I realized in your [comment](https://github.com/heremaps/harp.gl/issues/1382#issuecomment-599413564) in the Webpack issue).

```js
        baseUrl: "https://vector.hereapi.com/v2/vectortiles/base/mc",
        authenticationCode: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
        authenticationMethod: { // <------------------------ This was missing.
            method: AuthenticationMethod.QueryString,
            name: "apikey"
        },
```

**Comment by nzjony** [comment]
@trusktr , thanks again for looking into this. 

I notice that we can simplify the interface, why should you need to specify the `authenticationMethod`, when the format could decide... or at least the format supplies a default authentication method, which could be this apikey, see `getDefaultAuthMethod` on `OmvRestClient`

**Comment by engdevlab** [comment]
method: harp.AuthenticationMethod.QueryString
