### ISSUE TITLE
[bug] Surfaces culled although they should be in view

### ISSUE THREAD

**Issue by trusktr** [heremaps/harp.gl#1384]
**Describe the bug**

Looks like after certain interactions with the globe, the surfaces get erroneously culled at the edges of the screen.

**To Reproduce**

1. Zoom all the way in, out, in
2. Eventually it happens.

**Expected behavior**

There should be no culling at the edge of the viewport.

**Screenshots**

Here's a screen recording: https://youtu.be/Bv1pBGnFvuU

In the video, as I zoom in, you can see the black space come in from the edge of viewport.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Linux
 - Browser [e.g. chrome, safari] - Firefox
 - Version [e.g. 22] -

**Comment by nzjony** [comment]
@trusktr , do you have a screen recording available? I don't see any link in your bug report. I tried to reproduce quickly on Mac / Chrome & Firefox, but couldn't reproduce unfortunately.

Or do you have another idea how I could reproduce?

**Comment by atomicsulfate** [comment]
@trusktr Could you please share some screenshot or video showing the issue?

Thank you.

**Comment by trusktr** [comment]
Sorry, slow internet yesterday prevented me from uploading the video. I updated the original post with the link.

I can reproduce fairly often, usually by some combination of zooming all the way in or out with spherical globe projection and toggling 3D camera position (the "3D" button).

What I noticed is that when I zoom back out, the globe is no longer centered in the view, as if the camera has started to rotate around it's Y axis (in terms of Three.js, Y axis is usually up towards the top of the viewport, so the globe is shifted to the right or left instead of center).

**Comment by trusktr** [comment]
It is hard to reproduce. I am having difficulty reproducing right now. I'm not sure exactly what sequence of camera movements and navigations trigger it, but's it has happened a handful of times. I'll pay attention, and maybe over time I can pinpoint what I did to get into the state.

**Comment by nzjony** [comment]
@trusktr thanks for the video, now I understand the problem, it is the far plane which is cutting it.

I managed to also reproduce. I will discuss in our internal chat.

**Comment by nzjony** [comment]
Was also reported as #1558

**Comment by trusktr** [comment]
Looking forward to a fix. This is the number one thing bugging my because it's really the only thing that breaks the user experience. Everything else is amazing!!

**Comment by nzjony** [comment]
@trusktr , I will ask our product owner to bump the priority and try to pull it into the next sprint.

**Comment by nzjony** [comment]
I will try to look at this in the coming week.

**Comment by nzjony** [comment]
I introduced a regression, so this is still a valid bug.

**Comment by trusktr** [comment]
Awesome! I will circle back to try this out soon!
