### ISSUE TITLE
Tutorial is outdated. What's the new way to do things?

### ISSUE THREAD

**Issue by trusktr** [heremaps/harp.gl#1387]
Hello, the docs aren't aligned with what's release. The tutorial [mentions](https://developer.here.com/tutorials/harpgl/#method-1-linking-a-single-script-bundle-to-your-html-recommended) [several](add-tiled-geojson-from-a-server) [times]() to use the XYZ API which [is deprecated](https://github.com/heremaps/harp.gl/issues/1383) and I had no luck getting it to work.

Additionally the tutorial [mentions](https://developer.here.com/tutorials/harpgl/#change-the-maps-pitch-and-rotation) we can do things like

```js
    mapControls.maxPitchAngle = 90;
    mapControls.setRotation(6.3, 50);
```

but those APIs do not exist in the current release (TypeScript has a type error on the missing property and method).

It'd be great to keep the docs aligned with whatever is the current release, otherwise people may try to do things that simply won't work.

What should we write instead of

```js
    mapControls.maxPitchAngle = 90;
    mapControls.setRotation(6.3, 50);
```

?

**Comment by nzjony** [comment]
Thanks @trusktr  for pointing this out!

**Comment by musculman** [comment]
You are totally right, the tutorial on developer.here.com should be updated, because it references an old release.
Our own documentation, here in github.com, should also follow. The main README was updated, but as you already pointed out, we have missed a few things here and there. We will try to get it fixed.

**Comment by nzjony** [comment]
This issue is coming up in either this or the next sprint so hopefully we can fix this in the next month.

**Comment by nzjony** [comment]
Still in progress.....

**Comment by nzjony** [comment]
Ok, finally the tutorial: https://developer.here.com/tutorials/harpgl/ is up to date. Thanks @trusktr  for your issue !
