### ISSUE TITLE
Simplify authentication with the OmvDataSource via apikey

### ISSUE THREAD

**Issue by nzjony** [heremaps/harp.gl#1390]
**Is your feature request related to a problem? Please describe.**
See the following comment on issue #1383: https://github.com/heremaps/harp.gl/issues/1383#issuecomment-599858056

The question is, if the api format is specified, and there is a method: `getDefaultAuthMethod` on the `OmvRestClient` which specifies which is the default authentication method, and the GettingStartGuide.md shows an example with the `apikey`, should this now be the default method? It would at least make the `OmvDataSource` easier to create.

**Describe the solution you'd like**
Change the `getDefaultAuthMethod` to return a default authentication method using the apikey.

@musculman, what do you think? Have I missed something?

**Comment by musculman** [comment]
I agree with the simplification of how we handle different APIs.

In fact, we could simplify it even further by removing completely the APIFormat concept and stuff like that and support simple regex formulas, like:
`{hostname}/{x}/{y}/{z}/?{auth_param}={auth_value}`
so you could have it pretty generic without worrying about other stuff. In fact what we have today is a workaround until we support something like I have described.

**Comment by musculman** [comment]
Removing wontfix label as this is still needed

**Comment by nzjony** [comment]
Fixed in: https://github.com/heremaps/harp.gl/commit/5125074aecbbcd141d7c88914ee56dd6669d5ac7
