### ISSUE TITLE
support es module?

### ISSUE THREAD

**Issue by deyihu** [heremaps/harp.gl#1487]
**Is your feature request related to a problem? Please describe.**
```js
import { TextCanvas } from '@here/harp-text-canvas';

```

```shell
Error: 'TextCanvas' is not exported by node_modules\@here\harp-text-canvas\index.js

```

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zbigg** [comment]
It would be very helpful to add note about environment you want to use.

Nevertheless, we don't release pure ES modules right now for several reasons (among others, not yet fully stable ESM `package.json` interface, 3rdparty libraries that use CommonJS lack of support for ESM in workers).

Please consider using bundler like `webpack` that suppors both ESM and CommonJS.

**Comment by deyihu** [comment]
Thanks ，I use rollup
