### ISSUE TITLE
Is there an offline harp.js file ?

### ISSUE THREAD

**Issue by 15375296005** [heremaps/harp.gl#1514]
Is there an offline harp.js file?
How to deploy offline？

**Comment by nzjony** [comment]
@15375296005 sorry for the delay, I don't quite understand the question. You could download locally and use it offline.

**Comment by nzjony** [comment]
If you want to generate it locally, you can run `yarn build-bundle`, then go to the @here/harp.gl/dist folder and search for `harp.js`

**Comment by nzjony** [comment]
Closing as no response from @15375296005
