### ISSUE TITLE
Type Definition (.d.ts) for TypeScript

### ISSUE THREAD

**Issue by jplante** [heremaps/harp.gl#1526]
**Is your feature request related to a problem? Please describe.**
We'd like to integrate the library usage into our TypeScript project.

**Describe the solution you'd like**
We'd like to have a Type Definition file (.d.ts) that corresponds to the public types in the HarpGL library.

**Describe alternatives you've considered**
We've been developing our own but its both laborious, hard to maintain and not fully respective of the actual API as an official Type Definition.

**Comment by nzjony** [comment]
@jplante , thanks for your issue.

How are you using harp.gl in your project?

If I create a new direction and `npm add @here/harp-mapview`, then check in the `node_modules`, I can see: `MapView.js` and `MapView.d.ts` for example.

**Comment by zbigg** [comment]
As @nzjony mentioned, our first class packages (like `@here/harp-mapview`, `@here/harp-omv-datasoure` already contain typings).

Our [Getting started guide](https://github.com/heremaps/harp.gl/blob/master/docs/GettingStartedGuide.md#npm) already contains instructions how to use harp.gl in Typescript-based app that used webpack as bundler.

Given that  you're asking for typings i think you're referring to the only package that doesn't have typings bundled `@here/harp.gl`. This package was created with JS/HTML developers in mind so they can try `harp.gl` without overhead of setting up full webpack toolchain. We considered adding typing but there was just no need for this. There is even outdated PR (#833) for this.

**Comment by jplante** [comment]
Yeah, im trying to figure out how best to add them to a /typings directory in a single .d.ts file.

Im close but i don't quite have it working.  Its referring to the typings that are in the /node_modules folder.

**Comment by jplante** [comment]
We are struggling to get this up and running.

Essentially we are a TypeScript project that is wrapping the @here/Harp-xyz projects.  

We are using rollup as our compiler and need to be able to compile our own source and reference to your types against your definitions.  We'd like typing integrity across both the IDE and the compiler.  

When we are done compiling, our resulting script assumes its using your bundled JS - which wraps everything into a constant "harp" global variable as a namespace.  SO...

Essentially what we want is a single `.d.ts` file for all of the Harp projects that i can refer to in the `typings` folder, for which everything is wrapped under a "harp" namespace.

Effectively a proper single "d.ts" for the bundled JS

**Comment by nzjony** [comment]
@jplante , I think @zbigg sent the wrong link, he means the PR: #883 and not 833. Can you try this approach and if it works, feel free to open a PR so we can merge it

**Comment by zbigg** [comment]
@nzjony Thanks for pointing out the typo and linking proper PR.

Unfortunately, when i tried to create "single convenient" index.d.ts with all types bundled - i failed - none of rollup/webpack plugins worked for me at the time and i stepped back and wrote script that just remapped import declarations - again, result is in #883.

So i don't have any solution at hand.

As for now, we have plan to evaluate [api-extractor](https://www.npmjs.com/package/@microsoft/api-extractor) which as far as i know promises to bundle typings from bigger projects, so possibly would work also with harp.gl

**Comment by jplante** [comment]
Yes and it appears as though the branch that was attempted has been deleted.  So currently there is not "path forward".

**Comment by nzjony** [comment]
@jplante, we recently added support for api-extractor, see: https://github.com/heremaps/harp.gl/commit/e5a81909d443f78ae4f4aca80cb05b7dc7efacd6 and @robertoraggi mentioned to me that it supports rollup, see: https://api-extractor.com/pages/setup/configure_rollup/

However I would still like to know why you want to use our harp.js bundle and not our npm packages, especially because you mention you are using Typescript, probably I don't understand your setup.

**Comment by nzjony** [comment]
@jplante , @robertoraggi found a way to create the typings for harp.js: https://github.com/heremaps/harp.gl/pull/1588 however as I understand, it requires some changes to harp.js to work properly

**Comment by nzjony** [comment]
@jplante , @robertoraggi and I both got an example working locally using the types for harp.gl by using `types` in the `tsconfig.json`. Give it a try and let us know how you get on.

**Comment by nzjony** [comment]
@jplante the typings are not yet part of the package, you can generate them locally using `yarn workspace @here/harp.gl build-typings` if you want to try it out quick

Or wait for the next release, if you need it quick, we can make a patch release also.

**Comment by jplante** [comment]
@nzjony We'll wait on the next release and hope that its there.  Thanks :)

**Comment by nzjony** [comment]
@jplante , it is available in the latest release. I will close this issue and please let us know if you have any problems.
