### ISSUE TITLE
why does not work on github pages

### ISSUE THREAD

**Issue by caginagirdemir** [heremaps/harp.gl#1536]
I uploaded it to github pages but the map is not coming. There are appear only keys.

![1](https://user-images.githubusercontent.com/50463214/82125225-2c80db00-97ad-11ea-8558-2a22deba0da0.PNG)

Github pages are not running Python. Can problem relevant it?
thanks in advance.

**Comment by nzjony** [comment]
@caginagirdemir , what errors do you have in the console?

**Comment by caginagirdemir** [comment]
@nzjony 

![image](https://user-images.githubusercontent.com/50463214/82356073-c940b400-9a0b-11ea-867f-736e4f4e8ffb.png)
![image](https://user-images.githubusercontent.com/50463214/82356112-d6f63980-9a0b-11ea-9592-332c29a60fad.png)
![image](https://user-images.githubusercontent.com/50463214/82356156-e2e1fb80-9a0b-11ea-842d-3cf9aafea173.png)
![image](https://user-images.githubusercontent.com/50463214/82356178-ea090980-9a0b-11ea-9d1c-25461e8aab8a.png)

**Comment by caginagirdemir** [comment]
I don't understand why it doesn't work. I just loaded the sample code but i couldn't run a python via github.
I guess harp gl cannot run through github pages ?

**Comment by nzjony** [comment]
You have a screenshot with a missing `requirements.txt`, I guess that is necessary?

**Comment by nzjony** [comment]
I did a local git clone of your https://github.com/caginagirdemir/webglproject and opened the index.html, I get an issue with: `index.js:20 Uncaught TypeError: mapControls.setRotation is not a function`

**Comment by nzjony** [comment]
use the function `lookAt` instead, like: `mapView.lookAt({heading: 90})`, see: https://www.harp.gl/docs/master/doc/classes/harp_mapview.mapview-1.html#lookat

**Comment by nzjony** [comment]
We will fix the documentation: https://developer.here.com/tutorials/harpgl/ ASAP

**Comment by caginagirdemir** [comment]
Thank you @nzjony , I fixed
problem is here, `index.js:20 Uncaught TypeError: mapControls.setRotation is not a function`
I put to ahead of line of code that comment sign, and now working.

**Comment by nzjony** [comment]
Great to hear @caginagirdemir, and thanks for reporting the issue!

Can I close this issue if it is fixed?

**Comment by caginagirdemir** [comment]
Yes, you can.
