### ISSUE TITLE
Object rotation with Sphere projection enabled

### ISSUE THREAD

**Issue by native1989** [heremaps/harp.gl#1550]
**Describe the bug**
When I'm trying to add custom 3d objects to the tile I faced with strange behavior.
3D object rotation changes when projection type changes from planar to sphere. I can’t say that this is a bug(but it's not feature) because I'm trying to modify source code, but I can't find the way to correct rotation.
I will be glad if you can help me with this issue
![Screen Shot 2020-05-21 at 08](https://user-images.githubusercontent.com/807140/82520398-7d8e2780-9b3d-11ea-8c47-57db011f86c5.jpg)

```javascript
const scene = new THREE.Scene();
scene.renderOrder = 10000;
var pivot = new THREE.Group();
pivot.position.set(0,0,0);
scene.add( pivot );
const h = new THREE.AxesHelper(30);
h.renderOrder = 50000;
pivot.add(h);

const geometry = new THREE.PlaneGeometry( 20, 20, 32 );
const material = new THREE.MeshBasicMaterial( {color: 0xffff00, side: THREE.DoubleSide} );
const plane = new THREE.Mesh( geometry, material );
plane.renderOrder = 30000;

const sgeometry = new THREE.SphereGeometry( 5, 32, 32 );
const smaterial = new THREE.MeshBasicMaterial( {color: 0xff0000} );
const sphere = new THREE.Mesh( sgeometry, smaterial );
sphere.renderOrder = 40000;
pivot.add( sphere );

pivot.add( plane );
// data contains coordinates of object inside tile
pivot.position.set(data.x, data.y, data.z);
tile.objects.push(scene);
```

**Comment by nzjony** [comment]
You can use the `localTangentSpace` method in the `Projection` class to find the axes required to rotate an object such that it lies flat on the surface of the sphere, you can use it like this:

```
const box = new OrientedBox3();
// Position can be either a GeoCoordinatesLike or a Vector3Like in world space.
mapView.projection.localTangentSpace(position, box);
//... initialize grid
grid.setRotationFromMatrix(box.getRotationMatrix());
```

(Code adapted from `StylingTest.ts`).

**Comment by native1989** [comment]
Hi @nzjony, thanks for your answer. Your solution corrected object position in sphere projection, but I can't understand how keep initial object x-axis rotation. For simple object it's easy to wrap it in scene, but for instanced mesh I need somehow calculate rotation matrix based on initial rotation.

**Comment by nzjony** [comment]
@native1989 , I don't understand what you mean by "how keep initial object x-axis rotation", do you mean you want the same in planar projection?

**Comment by native1989** [comment]
@nzjony, I mean:
```js
plane.rotation.x = Math.PI / 2;
// ...
// and then I miss this rotation:
plane.setRotationFromMatrix(box.getRotationMatrix()); // Do the same for the sphere
```

**Comment by nzjony** [comment]
I see, you want to append the rotations. Probably best to use a Quarternion in that case. Also note, you can't use `plane.rotation.x`, you need to rotate around the `xAxis` of the box.

You would do something like:

```
const localTangentSpaceRotation = new Quarternion();
localTangentSpaceRotation.setFromRotationMatrix(box.getRotationMatrix())

const localXRotation = new Quarternion();
// make sure to use xAxis!!
localXRotation.setFromAxisAngle(box.xAxis, Math.PI / 2);

plane.quarternion.copy(localSpaceRotation).multiply(localXRotation).
```

or something like that.
