### ISSUE TITLE
There is a problem where examples

### ISSUE THREAD

**Issue by caginagirdemir** [heremaps/harp.gl#1552]
Everything is very nice, i watched this video https://www.youtube.com/watch?v=YhqpB58-wiQ
I did the things described here and created an example.
But the structures of the examples page code (harp.gl/docs/master/examples/) are very different.
I watched the video **for two hours** and now I cannot take advantage of the examples.
First of all, why are you doing so differently?
In examples the locations and spellings of the codes are different, constantly giving errors when I trying on index.js.
I learned via js bundle, and so unfortunately example codes are garbage

What can I do about it? are there any other examples?

I want to do something similar to this example. https://www.harp.gl/docs/master/examples/#datasource_features_polygons.html
It could be 2d.

if i can't do this , creating dots (geoJsonDataSource) from this site http://geojson.io/#map=2/20.0/0.0

Then I will add it as joseon file as in the video

I am determined to do this!

**Comment by nzjony** [comment]
hi @caginagirdemir , thanks for your issue and I appreciate your determination. I apologize for the frustration you are having with our documentation. We have changed the API, such that some of the methods that the video is referring to no longer exists (and actually the main tutorial here: https://developer.here.com/tutorials/harpgl is also out of date, I will fix it hopefully this week). We will learn from this and try to improve in future.

Yes, the examples show the most up to date API, so they are the best reference point for learning, however we will fix the tutorial also, because this is generally much easier to get started in the project.

**Comment by nzjony** [comment]
This is how you can see the source code of the examples:
<img width="696" alt="Screenshot 2020-05-25 at 10 06 43" src="https://user-images.githubusercontent.com/2533428/82792354-92392b00-9e6f-11ea-8b0e-ba2664e92527.png">

If I understand you correct, you want to render some geojson on the map? Here is another example that might help: https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fdatasource_geojson_choropleth.ts

Or can I help you more concretely?

**Comment by caginagirdemir** [comment]
thank you, 

I think I will make some more progress thanks to source.

I will benefit from this site. https://www.harp.gl/docs/master/doc/

Is there a class that  provide create the side panel like in the examples in this video? 

https://twitter.com/dbabbs/status/1206596849156538368

it will be easier if there is

**Comment by nzjony** [comment]
@caginagirdemir , no problems. Yes I hope the docs can help you, please let us know if you find something missing.

We don't have any such side panels like in the video you showed, but try reaching out to @dbabbs , maybe he can give you some hints how he did it.

**Comment by dbabbs** [comment]
The side panels in my Twitter video are just HTML overlays on top of the map. They aren't technically part of harp.gl, but rather something on top.

Eg, take this map: https://dbabbs.github.io/traffic/
The sidebar CSS can be found here: https://github.com/dbabbs/traffic/blob/master/index.css#L24

**Comment by caginagirdemir** [comment]
yes you can, I want to send away for you a beer when I come to Berlin.

**Comment by ninok** [comment]
Unfortunately github issues don't have a blocked by beer state so I close this issue :beers: :laughing:
