### ISSUE TITLE
Add more post-processing effects

### ISSUE THREAD

**Issue by harrycollin** [heremaps/harp.gl#1561]
I think it would be good to expand the range of post-processing effects to all that three.js offer by default. If this is not an option (I can see why you wouldn't want some of them), could we have access to the composer instance so that we can add our own passes?

What do others think about this? Is this unreasonable?

**Comment by nzjony** [comment]
Agreed, if there are more post-processing effects, it would make sense to support them.

We have a class: `MapRenderingManager` which wraps the post-processing effects, they would need to be expanded. Feel free to add a PR if you want to try this.

**Comment by harrycollin** [comment]
@nzjony Sounds good. I will see what I can do :)

**Comment by harrycollin** [comment]
@nzjony I haven't been able to make any significant progress on this :/ I'm happy to close the issue until it's re-addressed.

**Comment by nzjony** [comment]
@harrycollin , I captured this ticket in our JIRA and linked it here, so will close it for now and hopefully we can look at it soon.
