### ISSUE TITLE
Supports for WebGL2?

### ISSUE THREAD

**Issue by Mofangbao** [heremaps/harp.gl#1575]
Hi,is there any plan to support webgl2? I tried to pass WebGL2RenderingContext to MapViewOptions,but it's not works for all functionalities,especially for mesh with RawMaterial.
Thanks so much.

**Comment by nzjony** [comment]
@Mofangbao , we have an internal ticket to support this however we haven't yet started it, or planned when to work on it.

We could however consider to increase the priority, what do you want to achieve with it?

**Comment by J-Rojas** [comment]
I have a need to merge the Map renderer with my own Three.js based renderer which requires WebGL2 functionality. Would be great if you support this.

**Comment by nzjony** [comment]
@J-Rojas , thanks for your comment, I will try to raise the priority of the ticket. If you want however, feel free to create a PR if you want to fix it, it should just require fixing the shaders in `SolidLineMaterials.ts`.

**Comment by J-Rojas** [comment]
This is currently blocked by this issue: https://github.com/mrdoob/three.js/issues/19959 
The material code dynamically updates the programs using `#defines` and the way the code is structured, it would be a larger refactor to workaround that bug.

**Comment by nzjony** [comment]
@J-Rojas, thanks for linking to the bug!

**Comment by J-Rojas** [comment]
I saw the recent commits by @atomicsulfate to address some of these issues. I believe there is also code in SdfTextMaterial that also needs refactoring to support GLSL 3.0.

**Comment by Mofangbao** [comment]
@nzjony  Sorry for my delay response.  Actually I have some glsl codes based on WebGL2's 3D texture support,so only when harp.gl supports WebGL2, can I update them.
