### ISSUE TITLE
Change base style at runtime

### ISSUE THREAD

**Issue by panamantis** [heremaps/harp.gl#1590]
I'd like to modify the base map style properties at runtime based on user input. 

I know I can set the style during instantiation:

geoJsonDataSource.setStyleSet(styleSet);

But, it's unclear how to do this from the mapView class during runtime.

**Comment by nzjony** [comment]
@panamantis , thanks for your issue.

I spoke with @robertoraggi , the best idea is to set the theme again, something like

`mapView.theme = newTheme`

You can get the `newTheme` instance using the `ThemeLoader` class for example. This is slow, but we are in the process of optimizing it.

You can also consider to use dynamic properties, these are properties which you can control using the `setDynamicProperty` on the `MapView` class, however this only works with a small set of properties, see this example https://www.harp.gl/docs/master/examples/#object-picking.html or https://www.harp.gl/docs/master/examples/#datasource_geojson_styling_game.html also uses dynamic properties.

**Comment by gsavvid** [comment]
Updating the map style by setting a new theme doesn't seem to be working properly. At least not when the `newTheme` is a string url. I haven't tried updating it using a `Theme` obtained via the `ThemeLoader` but being able to update it using a url would be pretty convenient. Calling `map.update()` afterwards doesn't help either.

**Comment by nzjony** [comment]
@gsavvid , that, as far as I can tell from the code isn't currently supported, but would be a cool feature.

Let me know how you get on with using the ThemeLoader, here is an example: https://www.harp.gl/docs/master/examples/#getting-started_open-sourced-themes.html

**Comment by gsavvid** [comment]
Yep, updating the theme using `ThemeLoader` works just fine. I believe this issue can be closed.

**Comment by nzjony** [comment]
@gsavvid , great to hear!
