### ISSUE TITLE
geoJson has deviation on the map

### ISSUE THREAD

**Issue by PrUnSt** [heremaps/harp.gl#1609]
**Describe the bug**
geoJson has deviation on the map  in geojson-viewer.ts

**To Reproduce**
1、i load a wgs84 geojson file on the map ,but it has deviation
![1592294214(1)](https://user-images.githubusercontent.com/30542005/84747633-1784ab00-afea-11ea-8762-ae409372148b.jpg)

**Expected behavior**
the shape is on the correct locate

**Comment by nzjony** [comment]
@PrUnSt, do you have a copy of the geojson so we can take a look?

**Comment by PrUnSt** [comment]
[beijing.txt](https://github.com/heremaps/harp.gl/files/4785394/beijing.txt)

**Comment by PrUnSt** [comment]
> @PrUnSt, do you have a copy of the geojson so we can take a look?

[beijing.txt](https://github.com/heremaps/harp.gl/files/4785405/beijing.txt)

**Comment by nzjony** [comment]
@PrUnSt , I wonder if this is related to: https://en.wikipedia.org/wiki/Restrictions_on_geographic_data_in_China#GPS_shift_problem ?

At least I don't know of any special shifting for China.
