### ISSUE TITLE
Change extrusion scale

### ISSUE THREAD

**Issue by gsavvid** [heremaps/harp.gl#1625]
Is it possible to change the extrusion scale or disable extrusion altogether at runtime? My guess is that this has something to do with [ExtrusionFeature](https://www.harp.gl/docs/master/doc/modules/harp_materials.extrusionfeature-1.html) but I can't find any documentation or examples on how to apply this to my `MapView`.

**Comment by nzjony** [comment]
@gsavvid , thanks for creating an issue!

When you mean disable extrusion, do you want the buildings to appear already extruded? Or do you want to remove them? You can disable the animation, so that they immediately appear without animation:

`mapView.animatedExtrusionHandler.enabled = false;`

There isn't any way to change the extrusion scale, but you can play around with it, by looking at the `AnimatedExtrusionHandler.ts` file, specifically the `animateExtrusion` function.

**Comment by gsavvid** [comment]
Thanks a lot for the sharp response, @nzjony!

Regarding disabling extrusion: I would like to hide the 3D buildings altogether, not just disable their animation. To be more specific, I'm trying to replicate the [synchronized views example](https://www.harp.gl/docs/master/examples/#synchronized-views.html) except I want the two side views to be in 2D and only the middle one in 3D. Would this somehow be possible?

**Comment by nzjony** [comment]
@gsavvid , you have two options, you can remove it from the theme, or...

You can use the following method: https://www.harp.gl/docs/master/doc/classes/harp_mapview.tilegeometrymanager.html#disablekind and pass in "StandardGeometryKind.Building"

The `TileGeometryManager` can be found on the `MapView`, see: https://www.harp.gl/docs/master/doc/classes/harp_mapview.mapview-1.html#tilegeometrymanager

**Comment by nzjony** [comment]
Actually, you have three options, you can load the theme and then modify it at runtime, as:

```typescript
    const themePromise = ThemeLoader.load(themeUrl);
    if (disableBuildings === true) {
        themePromise.then(theme => {
            for (const decl of theme.styles!.tilezen!) {
                const style = decl as Style;
                // Here we disable the extruded buildings
                if (style.technique === "extruded-polygon") {
                    (style.technique as any) = "none";
                }
            }
        }
        return theme;
    }
```

And then pass the `themePromise` to the `MapView` when constructing it:

```typescript
mapView = new MapView({
    canvas,
    theme: loadedTheme,
    ....
}
```

**Comment by gsavvid** [comment]
Perfect, that's exactly what I was looking for. Thanks once again!

**Comment by nzjony** [comment]
Great you could solve your problem @gsavvid, hope I can see what you are up to soon!
