### ISSUE TITLE
WMTS / TMS Raster Tile data-source

### ISSUE THREAD

**Issue by jplante** [heremaps/harp.gl#1649]
**Is your feature request related to a problem? Please describe.**
Its common in a map experience to access a [WMTS](https://en.wikipedia.org/wiki/Web_Map_Tile_Service) or [TMS](https://en.wikipedia.org/wiki/Tile_Map_Service) standard data-service.  I see that WebTileDataSource exists but that appears to work exclusively with the HERE Tile Maps API (either via tileBaseUrl or an enumeration).  Providing an alternate URL Template throws an error because the `parseBaseUrl` has a Regex check that verifies it includes `/maptile/2.1/`.

**Describe the solution you'd like**
Native support for 3rd party WMTS / TMS data services through a Harp "data-source".

Perhaps this is on a roadmap that I'm unaware of.

**Describe alternatives you've considered**
Ive tried to use WebTileDataSource.  Ive also looked for a Canvas (see #1650) data source so that I can paint directly to my own canvas and pass in the result but no such feature exists.

**Comment by FraukeF** [comment]
Hi jplante, 

we are aware of the issue, that the current WebTileDataSource is tied very much to HEREs Data APIs.
I have created a PR (https://github.com/heremaps/harp.gl/pull/1652) that will extract the common code, so the WebTileDataSource can be used with any TileProvider,..

would something like in this example work for you: https://github.com/heremaps/harp.gl/blob/9fd4eb5cca975038e9b7f6f46506fd48c4577b94/%40here/harp-examples/src/datasource_webtile.ts

**Comment by FraukeF** [comment]
Hi @jplante 

We pushed a change to the WebTileDataSource, that enables any kind of data-service to be added as provider of the textures. Please have a look at the latest version of WebTileDataSource, it is still not available in the released packages, though, but will be probably in the next release.

**Comment by jplante** [comment]
Thanks!  I'll take a look at it and will see about getting a WTMS / TMS data-service to work once the package is available :)
