### ISSUE TITLE
Tutorial snippet out of date?

### ISSUE THREAD

**Issue by jplante** [heremaps/harp.gl#1660]
**Describe the bug**
When trying to follow along with how to implement data-driven styling, the snippet works at first but applying the filters seems to fail.

**To Reproduce**
Apply the first style appears to work:
```
map.addDataSource(globalRailroads).then(() => {
   const styles = [{
      "when": "$geometryType ^= 'line'",
      "renderOrder": 1000,
      "technique": "solid-line",
      "attr": {
         "color": "#D73060",
         "transparent": true,
         "opacity": 1,
         "metricUnit": "Pixel",
         "lineWidth": 1
      }
   }]

   globalRailroads.setStyleSet(styles);
   map.update();
});
```

However as soon as i apply any of the following types of filers things no longer work:
`"when": "$geometryType ^= 'line' && properties.status == 'Open'",`

Or even with the full snippet:
```
map.addDataSource(globalRailroads).then(() => {
   const styles = [
      {
         "when": "$geometryType ^= 'line' && properties.status == 'Open'",
         "renderOrder": 1000,
         "technique": "solid-line",
         "attr": {
            "color": "#50E3C2",
            "transparent": true,
            "opacity": 1,
            "metricUnit": "Pixel",
            "lineWidth": 1
         }
      },
      {
         "when": "$geometryType ^= 'line' && properties.status == 'Closed' || properties.status == 'Unknown'",
         "renderOrder": 1000,
         "technique": "solid-line",
         "attr": {
            "color": "#D63060",
            "transparent": true,
            "opacity": 1,
            "metricUnit": "Pixel",
            "lineWidth": 1
         }
      }
   ]
   globalRailroads.setStyleSet(styles);
   map.update();
});
```

**Expected behavior**
That the snippets would work as described.

**Screenshots**

**Desktop (please complete the following information):**
 - latest MacOS
 - Edge, Safari, Chrome

**Comment by nzjony** [comment]
thanks for reporting this @jplante , I have wanted to fix this tutorial for a while but always got distracted, will try to prioritise it soon.

**Comment by nzjony** [comment]
I've finished updating the tutorial, it just needs to be put into production.

**Comment by nzjony** [comment]
Tutorial is now live and up to date:https://developer.here.com/tutorials/harpgl/

Thanks @jplante again for your issue.
