### ISSUE TITLE
Problem displaying roads and names 

### ISSUE THREAD

**Issue by NicoBrug** [heremaps/harp.gl#1668]
**Shader error : Roads and names (country, street) are not displayed**
When I launch my web application, three js displays the buildings well but doesn't display everything else. I have  three js errors in the console. I tried on several computers the error remains the same and the roads are not displayed. I've tried several versions of three js, and I'm currently on the latest version. I've done the tutorial to integrate harp gl in a web application and I don't understand where the problem comes from (the buildings are well displayed). I tried different themes, and verified that the renderLabel was true. 
Do you know how I could fix this? 

**Configuration**
Grahic card : Quadro K2200/PCIe/SSE2
Mozilla : Version 68.5.0
Google Chrome :  Version 80.0.3987.132

**Web GL Shader error**
![pblshader](https://user-images.githubusercontent.com/25402899/86806193-ea6f6980-c078-11ea-9d2e-f80cd19bd86f.png)

**Map**
![ihm1](https://user-images.githubusercontent.com/25402899/86806333-0d9a1900-c079-11ea-88d4-3ea919ca69f9.png)

**Comment by nzjony** [comment]
@NicoBrug , thanks for the bug report! Are you using the latest release or the source code directly?

If you use the source code directly it should work, however the latest version doesn't work with three.js 0.118 unfortunately, but I fixed it here: https://github.com/heremaps/harp.gl/commit/546c0446a5ea49849770a4cf47dc6f7a8b9f1138 so you will need to wait for the next release and temporarily use three.js 0.117 until the next is out.

**Comment by NicoBrug** [comment]
Ok I switched to three js r117 and everything works fine. Thank you for your answer! 
Very good job anyway, it's really amazing.

**Comment by nzjony** [comment]
You're welcome, and thanks for taking an interest in harp.gl!
