### ISSUE TITLE
Object picking on Feature datasources.

### ISSUE THREAD

**Issue by harrycollin** [heremaps/harp.gl#1674]
Is it possible to interact with Feature datasources in the same way we use the object picking for base map features? I modified the object picking demo and added some GeoJSON but didn't manage to get anything. Am I right in thinking that the metadata for base map features is retrieved from the [userData ](https://threejs.org/docs/index.html#api/en/core/Object3D.userData)object on THREE.Object3D's?

Any thought's on this would be great to hear :)

**Comment by nzjony** [comment]
@harrycollin , yes we store the meta data in the `userData` as you mentioned.

Have you tried to debug the method `intersectMapObjects` and see what happens when picking the normal map objects as opposed to the GeoJSON objects? I guess we are doing some filtering which means that you can't see it.

**Comment by harrycollin** [comment]
@nzjony I finally go around to revisiting this. It seems the object picking does in fact find the GeoJSON which is great!. Closing this now.
