### ISSUE TITLE
Angular 9 Project w/ Harp.gl

### ISSUE THREAD

**Issue by gbrown97** [heremaps/harp.gl#1687]
**Describe the bug**
We are trying to create a MapView object within an Angular project using angular-builders/custom-webpack and harp-webpack-utils packages. The webpack config returned from harp-webpack-utils overrides the default Angular configuration, resulting in Angular not building the appropriate bundles: main.bundle.js, polyfills.bundle.js etc.

**Comment by vishalsdeshmukh** [comment]
Hi @gbrown97 , is your project hosted on github ? I can look at it and guide you further.

**Comment by gbrown97** [comment]
Here is a link to the repo:
https://github.com/gbrown97/harp-app
