### ISSUE TITLE
Simple Way to Use Local Satellite Tiles 

### ISSUE THREAD

**Issue by ninaaj** [heremaps/harp.gl#1698]
We want to use harp completely offline with our own data.  Will it be possible at some point to create a TileDataSource with a local path similar to this:

const tileDataSource = new TileDataSource({
        url: "../path/{z}/{x}/{y}.jpg",
        maximumLevel: 19,
        minimumLevel: 5
});

**Comment by nzjony** [comment]
@ninaaj , thanks for creating the issue.

Do you want to serve jpg as textures?

See: https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fdatasource_custom-texture-tile.ts

It serves a local texture, with the following:

```
function getTexture(tile: Tile): Promise<[THREE.Texture, CopyrightInfo[]]> {
        return Promise.all([new TextureLoader().load("resources/wests_textures/clover.png"), []]);
    }

    const webTileDataSource = new WebTileDataSource({
        dataProvider: {
            getTexture
        }
    });
```

I.e. you just need to implement the `getTexture` by loading from some local.

**Comment by ninaaj** [comment]
Thanks for getting back to me!

Yes, we want to use local Google Map tiles (>60,000 jpg files) as the map imagery/texture.

Can the code snippet from the custom texture tile example be modified to achieve that?

Also, is this method only possible in the latest dev? We are currently using the v17.2 release.

**Comment by nzjony** [comment]
@ninaaj , no problem!

Yes, it should be easy to modify the example to achieve that, you will need to find a way to map the tile to the resource, I guess by morton code ? You will also need to make sure that it uses the correct projection so that the textures line up correctly.

Yes, unfortunately that is only in the latest dev, we hope to make a release by the end of July however so you can use it from the packages.

**Comment by ninaaj** [comment]
@nzjony , thank you for the explanation

I'm looking forward to the next release!

**Comment by nzjony** [comment]
@ninaaj , happy to help, and all the best with your project and hope to see it live soon!

**Comment by nzjony** [comment]
@ninaaj, we have released the latest version: https://github.com/heremaps/harp.gl/releases/tag/v0.18.0, so you can use the packages :)
