### ISSUE TITLE
remove/replace buildings from map

### ISSUE THREAD

**Issue by dinovandeijzen** [heremaps/harp.gl#1705]
Dear team, 

Is it possible to remove a building from the map? 
I  notice that there is a removeObject() in the class:
https://developer.here.com/documentation/maps/3.1.17.0/api_reference/H.Map.html#removeObject

I haven't seen an example if it is possible with the buildings on the map, hoping to have guidance / pinpointer if this is possible.  The use case is that an old building on the map needs to be removed so the new project can be situated at that building plot. 
It would be of great help to know if the map has such flexibility.  

warmest regards,

Dino

the issue  that is tangent to my request:
https://github.com/heremaps/harp.gl/issues/1286

picking example:
https://www.harp.gl/docs/master/examples/#object-picking.html

**Comment by nzjony** [comment]
@dinovandeijzen , thanks for your issue.

That documentation is for a separate project "HERE Maps API for JavaScript", which is a bit different from harp.gl. harp.gl is primarily a 3D map renderer for the web. The "HERE Maps API for JavaScript" rather is designed to support a number of different use cases and focuses on providing a lot of functionality that is built in.

#1601 is a similar issue, we don't yet have the ability to remove a single building but it should not be too difficult to implement.

**Comment by dinovandeijzen** [comment]
Dear nzjony,

thank you to clarify on timely notice.

regarding:"#1601 is a similar issue, we don't yet have the ability to remove a single building but it should not be too difficult to implement"   <--   does this imply that at some day this will be possible but no expectation of time can be given or could I actively help/contribute in order to be able to implement this feature.  

short background:
Reason i ask is because i (as many other) find harp ideal to use , though as we work with new building plots or  new masterplans / district-layout the existing building massing changes hence the curiosity if Harp could be used or if it might not be the aim yet of the harp team currently to allow such functionality.

**Comment by nzjony** [comment]
@dinovandeijzen , no worries.

We would definitely consider to implement it, however we have some other priorities. It would need to be seen what business value it has, I have however created a ticket internally in our JIRA and will mention it in our team.

There is another ticket: https://github.com/heremaps/harp.gl/issues/1653 which is a bit related, you could take some data from OSM, upload it to an XYZ space and remove the buildings you want to avoid, it is a bit of a round about way to do it, but could work.

**Comment by dinovandeijzen** [comment]
thank you so much for the provided clarity,  
much much apreciated
