### ISSUE TITLE
Control data sources/layers from webpage + show data above points

### ISSUE THREAD

**Issue by parthgundi** [heremaps/harp.gl#1718]
Hi,
I'm creating a 3D map using harp-gl and have uploaded multiple layers of data onto the map. However, I'm facing 2 major issues at the moment and was looking for some help:

1. Can I select which layers of data to show on the map from the html webpage using tickboxes for example?
2. Can I add more data above points on the map e.g. if there is a point in Paris for a sold house, I want to show the address & price sold above the point where the house is located.

Thanks

**Comment by atomicsulfate** [comment]
Hi @parthgundi,

> 1. Can I select which layers of data to show on the map from the html webpage using tickboxes for example?

Is each layer of your data provided by a different `DataSource` instance ? If that's the case, then you can set the `enabled` property of the `DataSource` corresponding to a tickbox to true/false as part of your event listener.

> 2. Can I add more data above points on the map e.g. if there is a point in Paris for a sold house, I want to show the address & price sold above the point where the house is located.
> 
> Thanks

Yes, each one of those points with text could be a `TextElement` using the `labeled-icon` technique. If you're implementing your own custom DataSource, you can use the following code snippet as a guide:

`
            
            const projectedPoint = this.projection.projectPoint(geoPoint, new THREE.Vector3());
            const text = "Address and price"
            const textElement = new TextElement(
                text,
                projectedPoint,
                // text render style parameters
                {
                    fontSize: { unit: FontUnit.Pixel, size: 12, backgroundSize: 12 },
                    color: new THREE.Color("red")
                },
                // text layout style parameters
                {}
            );

            // Unique feature id identifying the text element. Two text elements sharing the same
            // feature id are considered to belong to the same map object (e.g. two icons
            // representing the same POI on different zoom levels). This feature id is also returned
            // when the text element is picked.
            textElement.featureId = ...;

            // Text drawing order is controlled by this attribute. The lower the value, the sooner
            // its drawn.
            textElement.renderOrder = ...;
            // Allow the text in the marker to overlap other text elements.
            textElement.mayOverlap = true;
            textElement.placement
            textElement.poiInfo = {
                technique: {
                    name: "labeled-icon",
                    renderOrder: this.nextFeatureId
                },

                renderTextDuringMovements: true, // draw text on camera movements.
                imageTextureName: "yourImageName", // A texture with than name must be registered in the PoiManager.
                textElement
            };
            // User data returned when the text element is picked.
            textElement.userData = { textElement };
            tile.addUserTextElement(textElement);`

Beforehand, you have to register the image that you want to use as an icon:
`
mapView.imageCache.addImage("yourImageName", <resource url>, true);
            mapView.poiManager.addImageTexture({
                name: "yourImageName",
                image: "yourImageName"
            });
`

**Comment by parthgundi** [comment]
Thanks @atomicsulfate

is it possible to use data through an API from ESRI/ArcGIS on harp.gl?

**Comment by nzjony** [comment]
@parthgundi , what format are these tiles in? MVT? Or some other format, it is theoretically possible.

**Comment by parthgundi** [comment]
@nzjony they are feature layers in ArcGIS or WMTS layers

**Comment by nzjony** [comment]
@parthgundi , sorry for the delay. We don't have any such example using a WMTS layer, though if there is enough demand, I'm sure we could implement it. If you like, feel free to open a PR and implement it yourself if you have time.
