### ISSUE TITLE
Can't access the harp.js with CDN

### ISSUE THREAD

**Issue by NicoBrug** [heremaps/harp.gl#1746]
Hello,

I can't access the harp.js bookstore anymore from the link : https://unpkg.com/@here/harp.gl/dist/harp.js. Has it been moved? 

The other links like the themes : https://unpkg.com/@here/harp-map-theme@latest/resources/berlin_tilezen_base.json are also inaccessible.

thanks

**Comment by nzjony** [comment]
@NicoBrug , when I click on the link: https://unpkg.com/@here/harp.gl/dist/harp.js, it takes me to: https://unpkg.com/@here/harp.gl@0.18.0/dist/harp.js which works fine. Can you try again?

Alternatively, you can build harp.js by yourself, just running `yarn build-bundle` in the root directory.

**Comment by sirakc** [comment]
try  ```window.harp``` or something similar, idea is to use ```window.``` because when using CDN to run any js library they just exist in the ```window``` so accessing them directly like ```harp.``` isn't going to work, you will have to change this to ```window.harp.something``` you can try this with any thing, not just harp.gl

**Comment by ninok** [comment]
@NicoBrug Closing this issue b/c it seems it was a temporary glitch with unpkg.com. Let us know if you still encounter any problems.
