### ISSUE TITLE
Adding CSS class to geojson file

### ISSUE THREAD

**Issue by sirakc** [heremaps/harp.gl#1750]
I have a simple request, I don't know if it exists or not but, I want to add ripple effect to my geojson file.

I have a list of points like this: 

 ```
"type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "properties": {
                "scalerank": 8,
                "natscale": 10,
                "labelrank": 3,
                "name": "Vatican City",
                "namepar": null,
                "namealt": null,
                "diffascii": 0,
                "nameascii": "Vatican City",
                "adm0cap": 1,
                "capalt": 0,
                "capin": null,
                "worldcity": 1,
                "megacity": 0,
                "sov0name": "Vatican (Holy Sea)",
                "sov_a3": "VAT",
                "adm0name": "Vatican (Holy Sea)",
                "adm0_a3": "VAT",
                "adm1name": "Lazio",
                "iso_a2": "VA",
                "note": null,
                "latitude": 41.9000122264,
                "longitude": 12.4478083889,
                "changed": 4,
                "namediff": 0,
                "diffnote": "Changed scale rank.",
                "pop_max": 832,
                "pop_min": 832,
                "pop_other": 562430,
                "rank_max": 2,
                "rank_min": 2,
                "geonameid": 6691831,
                "meganame": null,
                "ls_name": "Vatican City",
                "ls_match": 1,
                "checkme": 0,
                "featureclass": "Admin-0 capital"
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    12.453386544971766,
                    41.903282179960115
                ]
            }
        },
```

and I just want to add ripples like [THIS](https://codepen.io/FabienMotte/pen/gPKVxE) to the coordinates in this geojson, as you can see here I have coordinates of Vatican city and my style is:

```
export const geojsonTheme = [
    {
        when: "$geometryType == 'polygon'",
        technique: "fill",
        renderOrder: 10000,
        attr: {
            color: "#7cf",
            transparent: true,
            opacity: 0.8,
            lineWidth: 1,
            lineColor: "#003344"
        }
    },
    {
        when: "$geometryType == 'polygon'",
        technique: "solid-line",
        renderOrder: 10001,
        attr: {
            color: "#8df",
            metricUnit: "Pixel",
            lineWidth: 5
        }
    },
    {
        when: "$geometryType == 'point'",
        technique: "circles",
        renderOrder: 10002,
        attr: {
            size: 10,
            color: "#5ad",

        },
        

    },
    {
        when: "$geometryType == 'line'",
        technique: "solid-line",
        renderOrder: 10000,
        attr: {
            color: "#8df",
            metricUnit: "Pixel",
            lineWidth: 5
        }
    }
];


precisely it used the 3rd geometryType which is point and it renders a blue point, any way to make that point ripple? in any way possible?

```

**Comment by nzjony** [comment]
@sirakc , thanks for the issue.

I spoke with a colleague @robertoraggi and this should be possible.

You can use a `dynamic-property`, i.e. you would set the `size` to be something like: `”size”: [“get”, “size”, [“dynamic-properties”]]`

And then you can set the size as: `map.setDynamicProperty(“size”, Math.sin(time) * 5);`

Does that work?

**Comment by sirakc** [comment]
Hi @nzjony ! I am a bit new to the geojson world, can you guide a little more?, my project is pretty simple right now, just a  globe with a theme on it, just like [harp.gl's example on geojson](https://www.harp.gl/docs/master/examples/#datasource_features_lines-and-points.html) and now just like you said, changing the size of the circle will make it look like a ripple, so the question is, where and how to update it,  like do I put the `map.setDynamicProperty(“size”, Math.sin(time) * 5);` do I put it inside an event that updates the map? I have an event that i use to update the map and make it rotate 

```
map.addEventListener(MapViewEventNames.AfterRender, () => {
        options.target = new GeoCoordinates(0, options.target.lng + 0.1);
        map.lookAt(options);
        map.update();

    });
```


so I am trying this from my side and my findings will be coded here and if you have time please do share an example, so that I can get an ideas of properties and where to put them, also do share if you know any docs/reference guide to these properties that are changable, like 

{
        when: "$geometryType == 'point'",
        technique: "circles",
        renderOrder: 10002,
        attr: {
            size: 10,
            color: "#121275",

        },
        

    }

so that i can know what properties can be added

**Comment by nzjony** [comment]
@sirakc , would he happy to help.

Best change `AfterRender` to `Render`, i.e. you set the lookAt and the dynamic property before rendering.

Also, you don't need the `map.update()` in the event listener. You can, outside of the event listener call `map.beginAnimation()` onece and then at least you will get the render calls without having to manually call `update`.

In your case, you would change the value `10`, with the expression: `[“get”, “size”, [“dynamic-properties”]]`, then you would need to set the value each frame in the `Render` event listener.

**Comment by sirakc** [comment]
@nzjony I did this and it worked changed the animation, things are running smoother.

I would like to know if there is an official method for adding markers something you guys recommend, or change the render of the geojson points, you know how the geojson refers to the technique of rendering the geojson coordinates 

 {
        when: "$geometryType == 'point'",
        technique: "circles", //<-- HERE! referring to make a circle
        renderOrder: 10002,
        attr: {
            size: ["get", "size", ["dynamic-properties"]],
            color: "#121275",
        },
    },


so can we change that to a separate three.js object or something? like a square

**Comment by nzjony** [comment]
@sirakc , what do you mean by Markers? Do you mean 2D icons? Take a look at: https://github.com/heremaps/harp.gl/issues/1718#issuecomment-664254883

We also have the idea of `mapAnchors` on the `MapView`, see: https://www.harp.gl/docs/master/examples/#threejs_animation.html, if you have a separate three.js object, you can add it here.

Does that help, or did I misunderstand your question?

**Comment by sirakc** [comment]
@nzjony  hey, a bit late reply, yea 2D icons is what I am talking about what are those 2D icons made of? html tags? three js objects?
cause then we can find out what can be done with that icon, what property can be changed

**Comment by sirakc** [comment]
I found this newly added example to the latest harp.gl version of August 23,2020,

https://www.harp.gl/docs/master/examples/#getting-started_hello-world_npm.html

this example shows how to add markers over json data

**Comment by nzjony** [comment]
Thanks @ninok  for the example!
