### ISSUE TITLE
Toggle layers on & off

### ISSUE THREAD

**Issue by parthgundi** [heremaps/harp.gl#1774]
Hi,

I am trying to toggle layers on & off and am unsure if I am along the right lines with this code.

`var datasource = ['xxxx', 'xxxx'];
 
// set up the corresponding toggle button for each layer
for (var i = 0; i < datasource.length; i++) {
   var name = getDataSourcebyName(datasource[i]);
 
var link = document.createElement('a');
link.href = '#';
link.className = 'active';
link.textContent = name;
 
link.onclick = function(e) {
var clickedLayer = this.textContent;
e.preventDefault();
e.stopPropagation();
 
var visibility = datasource.enabled();
 
// toggle layer visibility by changing the layout object's visibility property
if (visibility === 'true') {
visibility = 'false';
this.className = '';
} else {
this.className = 'active';
visibility = 'true';
}
};
 
var layers = document.getElementById('menu');
layers.appendChild(link);
}
`

**Comment by ninok** [comment]
Hi @parthgundi,
I think there are some mistakes in the code you posted.
1. It should be `var visibility = datasource.enabled;` since it's a property.
2. visibility is a boolean, so it should be `visibility = false;` instead of `visibility = 'false';` (same for the `true` case)
3. booleans are no references in JavaScript so you have to set the visibility again after you changed it (`datasource.enabled = visibility`)

Hope that helps. Let me know if you still have problems.

**Comment by parthgundi** [comment]
Hi @ninok ,

Thanks. I'm trying to create something similar to this: https://www.harp.gl/docs/master/examples/#datasource_features_polygons.html

Where the years at the bottom are names of datasources that I can be put onto the map or removed. Any help on how to change this code appropriately would be appreciated.

**Comment by ninok** [comment]
Hi @parthgundi ,
the example you mentioned is adding and removing datasources based on their visibility. In your code snippet you are enabling/disabling them. Both approaches are fine.
How did you setup your application? I strongly suggest to use Typescript so you get full IDE support.
You can use our app generator for that: `npm init @here/harp.gl-app`

**Comment by parthgundi** [comment]
Hi @ninok,

Yes I was using Javascript to set up the application until now - will have a look at typescript.

**Comment by ninok** [comment]
@parthgundi I will close this ticket now b/c there is no issue in harp. Please create another one or contact us via slack if you have further questions.
