### ISSUE TITLE
index.js:1 MapView: Failed to load theme: Error: failed to create expression from: undefined Error: failed to create expression from: undefined

### ISSUE THREAD

**Issue by sirakc** [heremaps/harp.gl#1796]
I have an already running harp.gl map, the harp.gl map is good but its documentation thinks that I am born with knowledge of harp.gl and three.js
thanks to harp.gl for creating seperate example on request.

with that said, here is my problem

I have a harp.gl react based example (being a react project doesn't really matter) and I can't load my theme 

here is my package.json

`{
  "name": "harpgl",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@here/harp-datasource-protocol": "^0.17.2",
    "@here/harp-features-datasource": "^0.17.0",
    "@here/harp-geoutils": "^0.17.2",
    "@here/harp-map-controls": "^0.17.2",
    "@here/harp-mapview": "^0.17.2",
    "@here/harp-omv-datasource": "^0.17.2",
    "@here/harp-vectortile-datasource": "^0.19.0",
    "@here/harp-webtile-datasource": "^0.17.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "bootstrap": "^4.5.2",
    "es6-tween": "^5.5.11",
    "jquery": "^1.12.4",
    "popper.js": "^1.16.1",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-globe": "^5.0.2",
    "react-scripts": "3.4.1",
    "react-scroll-horizontal": "^1.6.4",
    "three": "^0.119.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {}
}
`

and this is my [theme](https://gofile.io/d/5uyQNg):

and I am just getting this error:

`index.js:1 MapView: Failed to load theme: Error: failed to create expression from: undefined Error: failed to create expression from: undefined`

I did pass the theme, it worked perfectly with previously running harp.gl, I just updated the harp.gl because of new things they did, so I am using the latest version of everything harp.gl as of August 23 2020. 

how can theme be undefined if I defined it 

this is the full error log:
[localhost-1598286517978.log](https://github.com/heremaps/harp.gl/files/5119128/localhost-1598286517978.log)

**Comment by sirakc** [comment]
Hello, I found the solution in the wild, its to update your theme.json file to match the pattern of the latest one, the one I was using was outdated, if someone is having this issue and is lost in the wild, I feel you, here

https://github.com/heremaps/harp.gl/blob/master/%40here/harp-map-theme/resources/berlin_tilezen_night_reduced.json

go to this link, this link will give you the outline that is needed to make this work, change the settings from there

**Comment by nzjony** [comment]
@sirakc , thanks for your perseverance, and good job on resolving the issue!
