### ISSUE TITLE
decoder.bundle.js should be easy to find

### ISSUE THREAD

**Issue by sirakc** [heremaps/harp.gl#1797]
I m trying this example https://www.harp.gl/docs/master/examples/#datasource_geojson_points.html

and its not working because of one error:
```
WorkerChannel: WorkerService: [worker-service-manager]: Failure Error: unknown targetServiceType requested: 'vector-tile-decoder'
WorkerChannel: WorkerService: [worker-service-manager]: Failure Error: unknown targetServiceType requested: 'geojson-tiler'
MapView: Failed to connect to datasource geojson: Error: unknown targetServiceType requested: 'vector-tile-decoder'
```

basically  the map is running without any error but when I try to do this:

```
const geoJsonDataProvider = new vectortileGeoJsonDataProvider(
      "points",
      new URL("./points.json", window.location.href)
    );
    const geoJsonDataSource = new vectortileVectorTileDataSource({
      dataProvider: geoJsonDataProvider,
      name: "geojson",
      styleSetName: "geojson",
    });
    map.addDataSource(geoJsonDataSource);
```

so the error is generating from here, it can't seem to find  the vector-tile-decoder and geojson-tiler, what to do here?

**Comment by FraukeF** [comment]
Hi @sirakc , 

I am sorry, you are encountering issue running the examples. 
Regarding the decoders, how have you set up your project?
Usually the decoders run in an own WebWorker, that you ll have to set up, see:
[getting started: decoderbundle](https://github.com/heremaps/harp.gl/blob/master/docs/GettingStartedGuide.md#decoder-bundle)

If you are creating a new project anyway, you might want to consider to use the harp.gl app generator, which will take care of setting up the decoder bundle for you, see:

[harp.gl-app generator](https://github.com/heremaps/harp.gl#node-modules)

**Comment by sirakc** [comment]
@FraukeF hello :) I am had a working example with version 0.17.0 but now I updated to 0.19.0 and changed some things around and I am getting messages randomly in random places which indicate some files are missing. I am using React JS version 16.13.1 as of August 26 2020, can you please make me an example? I

 am just trying to run an example, I have my API key and everything with me, I am using encountering random errors with the next code.

I Just want a sphere projection with [geojson points example](https://www.harp.gl/docs/master/examples/#datasource_geojson_points.html) implemented, thats all


I love harp gl and all the flexibility it offers 🥇

**Comment by sirakc** [comment]
@FraukeF message that shows up:
`VectorTileDataSource: Unable to create decoder service in worker. Use  'OmvTileDecoderService.start();' in decoder script.`
where is the decoder script? I know that in the @here/harp-examples has a folder for decoder on github but who calls it? the source says that default decoder will be chosen, to fix this problem I added `decoder: new VectorTileDecoder(),` in the setup process

```
map = this.initializeMapView("map_canvas");
    const OMV = new vectortileVectorTileDataSource({
      baseUrl: "https://vector.hereapi.com/v2/vectortiles/base/mc",
      apiFormat: vectortileAPIFormat.XYZOMV,
      styleSetName: "tilezen",
      maxDataLevel: 17,
      authenticationCode: apiKey,
      authenticationMethod: {
        method: vectortileAuthenticationMethod.QueryString,
        name: "apikey",
      },
      // decoder: new VectorTileDecoder(),
      copyrightInfo,
    });
    map.addDataSource(OMV);
```

after that the code runs but then when I see its laggy and stutters so I look into console and this shows up:


`MapViewUtils: estimateMeshSize: unidentified material:  MapMeshStandardMaterial {uuid: "EC0DF723-2855-4F7E-83D7-75FF430D3C20", name: "", type: "MeshStandardMaterial", fog: true, blending: 1, …}alphaMap: nullalphaTest: 0aoMap: nullaoMapIntensity: 1blendDst: 205blendDstAlpha: nullblendEquation: 100blendEquationAlpha: nullblendSrc: 204blendSrcAlpha: nullblending: 1bumpMap: nullbumpScale: 1clipIntersection: falseclipShadows: falseclippingPlanes: nullcolor: Color {r: 0.4235294117647059, g: 0.5803921568627451, b: 0.47058823529411764}colorWrite: truedefines: {STANDARD: "", ZFIGHTING_WORKAROUND: ""}depthFunc: 3depthTest: falsedepthWrite: truedisplacementBias: 0displacementScale: 1dithering: falseemissive: Color {r: 0, g: 0, b: 0}emissiveIntensity: 1emissiveMap: nullenvMap: nullenvMapIntensity: 1flatShading: falsefog: truelightMap: nulllightMapIntensity: 1map: nullmetalness: 0metalnessMap: nullmorphNormals: falsemorphTargets: falsename: ""normalMap: nullnormalMapType: 0normalScale: Vector2 {x: 1, y: 1}onBeforeCompile: ƒ (...args)opacity: 1polygonOffset: falsepolygonOffsetFactor: 0polygonOffsetUnits: 0precision: nullpremultipliedAlpha: falserefractionRatio: 0.98roughness: 1roughnessMap: nullshaderDefines: {STANDARD: "", ZFIGHTING_WORKAROUND: ""}shaderUniforms: {fadeNear: Uniform, fadeFar: Uniform, extrusionRatio: Uniform}shadowSide: nullside: 0skinning: falsestencilFail: 7680stencilFunc: 519stencilFuncMask: 255stencilRef: 0stencilWrite: falsestencilWriteMask: 255stencilZFail: 7680stencilZPass: 7680toneMapped: truetransparent: falsetype: "MeshStandardMaterial"userData: {mapAdapter: MapMaterialAdapter}uuid: "EC0DF723-2855-4F7E-83D7-75FF430D3C20"version: 0vertexColors: falsevertexTangents: falsevisible: truewireframe: falsewireframeLinecap: "round"wireframeLinejoin: "round"wireframeLinewidth: 1_listeners: {dispose: Array(1)}displacementMap: (...)extrusionRatio: (...)fadeFar: (...)fadeNear: (...)id: 171overdraw: (...)removeDiffuseLight: (...)shading: (...)stencilMask: (...)wrapAround: (...)wrapRGB: (...)get extrusionRatio: () => {         return this.getExtrusionRatio();       }set extrusionRatio: val => {         this.setExtrusionRatio(val);       }get fadeFar: () => {         return this.getFadeFar();       }set fadeFar: val => {         this.setFadeFar(val);       }get fadeNear: () => {         return this.getFadeNear();       }set fadeNear: val => {         this.setFadeNear(val);       }__proto__: MeshStandardMaterial`


telling that something is missing from mapview utils

**Comment by sirakc** [comment]
@FraukeF the errors occurs here:

`

overrideMethod | @ | react_devtools_backend.js:2273
-- | -- | --
  | warn | @ | ConsoleChannel.js:35
  | warn | @ | Logger.js:50
  | estimateMaterialSize | @ | Utils.js:1291
  | estimateMeshSize | @ | Utils.js:1379
  | estimateObject3dSize | @ | Utils.js:1190
  | computeResourceInfo | @ | Tile.js:858
  | get memoryUsage | @ | Tile.js:206
  | (anonymous) | @ | VisibleTileSet.js:48
  | shrinkToCapacity | @ | LRUCache.js:152
  | shrinkToCapacity | @ | VisibleTileSet.js:204
  | updateRenderList | @ | VisibleTileSet.js:466
  | render | @ | MapView.js:2470
  | renderLoop | @ | MapView.js:2365
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | renderLoop | @ | MapView.js:2381
  | requestAnimationFrame (async) |   |  
  | startRenderLoop | @ | MapView.js:2395
  | update | @ | MapView.js:1828
  | lookAtImpl | @ | MapView.js:2161
  | setupCamera | @ | MapView.js:2837
  | MapView | @ | MapView.js:431

`

**Comment by FraukeF** [comment]
Hi @sirakc ,

I am very happy to hear, that you like harp.gl, thats amazing. 
Unfortunately harp.gl still has a very volatile API, but we are working on making it more stable, therefore the update from 0.17 to 0.19 brought so much changes, that it broke your running example. 

You were asking, where to find the decoder script.. per default you should find it here:
(./decoder.bundle.js)[https://www.harp.gl/docs/master/doc/interfaces/harp_mapview.mapviewoptions-1.html#decoderurl]

If you set the Decoder directly in the VectorTileDatasource, it will not run in a WebWorker.

As it looks like quite some things got changed for the example code with the update from 0.17 to 0.19 and you want to "just" run an example, I would recommend you set up a new project with the 

harp.gl-app generator and past the example code there. 

Please let me know if that works for you.

**Comment by sirakc** [comment]
I went back to 0.117.0, more stable, hoping for react implementation soon, maybe make a zip file that has already everything in it, just extract and use
