### ISSUE TITLE
MapView is not fully garbage collected after dispose()

### ISSUE THREAD

**Issue by J-Rojas** [heremaps/harp.gl#1798]
**Describe the bug**

When attempting to clean up all the memory of the MapView, the MapView is still retained by several global data structures inside the Harp.gl library.

The "Events" data structures are global constants that retain the MapView because Three.js applies the MapView object to  the `target` property of the event when it is dispatched. This target property is not unset. This causes the MapView to linger in memory most likely until the next MapView is constructed that replaces the lingering references.

I would recommend these Events be placed inside the MapView/DataSource as private members to solve this problem.

**To Reproduce**

Build a MapView, attach it to the DOM, then detach and `dispose()`

**Expected behavior**

A look at Chrome memory management tool should show the MapView is no longer retained in memory.

**Comment by FraukeF** [comment]
@J-Rojas Thanks a lot for reporting it, we will look into it and let you know when it is resolved

**Comment by ninok** [comment]
Fixed with https://github.com/heremaps/harp.gl/pull/1807
