### ISSUE TITLE
Slow tile loading when 'heavy' MapAnchor visible

### ISSUE THREAD

**Issue by harrycollin** [heremaps/harp.gl#1815]
I've just upgraded to 0.19.0 and have noticed that having a relatively heavy (i.e lots of materials/geometry) MapAnchor is making new tile loading extremely slow, sometimes even not loading at all. I tested this by having a visibility toggle for my MapAnchor. When the MapAnchor is visible the tile loading is really slow, sometimes not even loading surrounding tiles. By simply toggling it's visibility the tiles instantly load. This wasn't the behaviour in previous versions, however I did upgrade from all the way back 0.14.0. Is this likely a bug or misuse on my side?

[Here ](https://imgur.com/r75r0Kp)is a short gif demonstrating the visibility toggle and how the tile loading is affected, starting with the MapAnchor being visible,. As you can see after hiding the anchor the tiles load almost instantly. 

 - OS: Windows 10
 - Browser: Chrome
 - Version: 85.0.4183.83 (Official Build) (64-bit)

**Comment by harrycollin** [comment]
I'm closing this issue for now since I think it needs more testing on my side. Will reopen if it persists.

**Comment by harrycollin** [comment]
After further investigation it appears something changed in 0.18.0 that causes this. I've tested with 0.17.2 and it appears to stop here. Did anything change in 0.18.0 that might affect this?

**Comment by nzjony** [comment]
@harrycollin , sorry I didn't get around to looking into this. I will ask in the team as I am off tomorrow, or I look into it next week.

**Comment by harrycollin** [comment]
@nzjony no worries :)

**Comment by harrycollin** [comment]
As I'm using react for my apps this issue might be related to [this](https://github.com/slaylines/harp.gl-react-example/issues/6). I've noticed significant performance issues since upgrading to newer harp.gl releases after 0.14.0. I recommend building the app on [here](https://github.com/slaylines/harp.gl-react-example) and seeing the frame-rate when going close to the ground (high zoom levels). I apologise if this changes the original cause of this issue as I fear it's a byproduct of using harp.gl with react incorrectly.

**Comment by nzjony** [comment]
@harrycollin , I will give it a try now.

**Comment by harrycollin** [comment]
@nzjony i forgot to mention - edit app.js line 13 to increase max zoom level

**Comment by nzjony** [comment]
@harrycollin , I checked the performance in Chrome but was getting 60 FPS, see: https://youtu.be/Gg_GhHrmIt8

Can you try finding where it slows down and then record the performance? I would like to see what function is taking so much time.

**Comment by harrycollin** [comment]
@nzjony That's strange. I've recorded a video [here](https://www.youtube.com/watch?v=sxDqMmylsdY&feature=youtu.be) to demonstrate the problem. I have linked the chrome performance profile as well. Let me know what you think.

**Comment by nzjony** [comment]
I loaded the perf output, but I just see a lot of "value".

Where the frames take ~ 370ms, what is this function that takes so long?

<img width="351" alt="Screenshot 2020-09-07 at 16 30 02" src="https://user-images.githubusercontent.com/2533428/92397703-90962900-f127-11ea-8115-796cd71e316a.png">

**Comment by harrycollin** [comment]
@nzjony I'm not sure about this one. It believe it's due to react bundling code at build-time.

**Comment by nzjony** [comment]
@harrycollin , I just ran `yarn start`, I will try building it and let you know how I get on.

**Comment by nzjony** [comment]
@harrycollin , I can reproduce the issue locally. Very strange. I will ask in the team if they know.

**Comment by harrycollin** [comment]
@nzjony I will try to produce a better profile as well

**Comment by harrycollin** [comment]
@nzjony here is a profile. With react you have to include the --profile flag when running npm build. Download [here](https://drive.google.com/file/d/13fBrY0NSismJUJoXUQXG2Mz0YIeJCdlR/view?usp=sharing).

**Comment by nzjony** [comment]
@harrycollin , please grant me access

**Comment by harrycollin** [comment]
@nzjony I've updated the link.

**Comment by nzjony** [comment]
@harrycollin , I tried to reproduce the slow down with our internal example but couldn't. I recommend we wait until it is made public and then you retest and we see if there is still some issue. I'm not a react expert so unfortunately can't give you any idea how to progress forwards.

**Comment by harrycollin** [comment]
@nzjony thank you for trying! Am I able to see a preview of the internal example? Specifically any webpack and decoder configuration.

**Comment by nzjony** [comment]
@harrycollin , not yet unfortunately, it has to go through the legal process :(. I will try to get an idea how long it will take.

**Comment by harrycollin** [comment]
@nzjony I understand. Hopefully not too long!

**Comment by nzjony** [comment]
@harrycollin , I spoke with @robertoraggi , he said that:

> `yarn build` creates an es5 bundle and yarn start keeps the code in es2017. harp.gl in es5 may run slower than es0217 because many features that we use (like await/async, generators, classes, …) are emulated.

**Comment by harrycollin** [comment]
@nzjony this is interesting. Is there anything I can do to help?

**Comment by nzjony** [comment]
@harrycollin , we had another idea, instead of creating a new repository, we can add the react app as a yeoman generator, so that means we don't have to do through any legal loopholes. I will start work on it and let you know when we have something up.

**Comment by nzjony** [comment]
@harrycollin , I spoke with @robertoraggi  and he suggested to:

1. run `yarn eject`
2. open `webpack.config.js` and search for `test: /\.(js|mjs)$/,`
3. Replace 

```
{
              test: /\.(js|mjs)$/,
              exclude: /@babel(?:\/|\\{1,2})runtime/,
              loader: require.resolve('babel-loader'),
              options: {
                babelrc: false,
                configFile: false,
                compact: false,
                presets: [
                  [
                    require.resolve('babel-preset-react-app/dependencies'),
                    { helpers: true },
                  ],
                ],
                cacheDirectory: true,
                // See #6846 for context on why cacheCompression is disabled
                cacheCompression: false,
                
                // Babel sourcemaps are needed for debugging into node_modules
                // code.  Without the options below, debuggers like VSCode
                // show incorrect code and set breakpoints on the wrong lines.
                sourceMaps: shouldUseSourceMap,
                inputSourceMap: shouldUseSourceMap,
              },
            }
```

With:

```
{
              test: /\.(js|mjs)$/,
              exclude: /@babel(?:\/|\\{1,2})runtime/,
              use: {
                loader: "babel-loader",
                options: {
                  presets: [
                    ["@babel/preset-env", { targets: { chrome: "85" } }],
                    "@babel/preset-react",
                  ],
                },
              },
            },
```

I tested it quickly and the performance seems to be improved.

**Comment by harrycollin** [comment]
@nzjony thank you! I'll test it on my end

**Comment by harrycollin** [comment]
@nzjony @robertoraggi This works nicely, thank you! However I must ask is there a way to do this without ejecting? It would be my last resort.

**Comment by nzjony** [comment]
as far as I know, from what @robertoraggi was telling me, `react-scripts` transpiles to es5, so I think you are stuck with having to eject for now until we can investigate the performance bottleneck for es5

**Comment by harrycollin** [comment]
Okay I see. I'll try a few things and post a solution if I find one. Is your internal react example ejected then?

**Comment by robertoraggi** [comment]
try to change `"browserslist"` in the generated `package.json`. The default value for `production` targets browsers that don't have es6 support.

```json
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
```

**Comment by harrycollin** [comment]
@robertoraggi Thank you! This appears to have resolved the horrible performance after a quick build. I didn't know this affected the compilation process. Can you explain a bit more?

**Comment by robertoraggi** [comment]
@harrycollin CRA based projects use babel to transpile the code
so you can use the babel's browserslist integration to target modern JS
https://babeljs.io/docs/en/babel-preset-env#browserslist-integration
