### ISSUE TITLE
threejs Raycaster failure

### ISSUE THREAD

**Issue by datouzhan** [heremaps/harp.gl#1820]
**Describe the bug**
I want to achieve the function of picking up three objects. Refer to the example of ray intersection on the official website，but the returned result is empty. And then, i try to use the method of pickingraycaster to picking object,it is obvious that the return result is empty.

**To Reproduce**
1. Long press on cube
2.return nothing

**Expected behavior**
I hope to pick up objects like the threejs example

**Screenshots**
![image](https://user-images.githubusercontent.com/20176393/92208011-dbf8cf00-eebc-11ea-8a07-393ebf4f5c03.png)
![image](https://user-images.githubusercontent.com/20176393/92208028-e4e9a080-eebc-11ea-93fe-0df8d5c3a16e.png)

**Desktop (please complete the following information):**
 - OS: [e.g.Window ]
 - Browser [e.g. chrome, chrome]
 - Version [e.g. Apache License 2.0]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, chrome]

**Additional context**

**Comment by nzjony** [comment]
Thanks for reporting @datouzhan , I have made a fix.

**Comment by datouzhan** [comment]
> 感谢您报告@datouzhan，我已修复问题。

Thank u.
