### ISSUE TITLE
Can we get an update on the harp.gl API key getting process?

### ISSUE THREAD

**Issue by sirakc** [heremaps/harp.gl#1824]
Harp.gl has an existing guide to [acquiring credentials](https://developer.here.com/tutorials/harpgl/#acquire-credentials) but there has been some small changes inside the Here Developer website and I feel a newer version of the doc will be cool.

its a bit confusing to know where to do in the website, cause I see an XYZ studio, I see data hub console and its all overwhelming.

can there be please a simply step by step guide with explanation cause we would love to know the process and learn more, genuinely interested in all things harp.gl

**Comment by nzjony** [comment]
@sirakc , I'm updating the tutorial and just waiting for it to get published.

When it is updated I will let you know.

**Comment by nzjony** [comment]
@sirakc , I have pushed a draft PR here: https://github.com/heremaps/harp.gl/blob/99881a21c9d1420bfbe0cbee805b2de4f6c00ef0/docs/tutorial/README.md

This is just temporary, the tutorial will be eventually hosted here: https://developer.here.com/tutorials/harpgl

Which contains the tutorial, please feel free to take a look and please give me any feedback as to how I can improve it, especially the [acquiring credentials](https://github.com/heremaps/harp.gl/blob/99881a21c9d1420bfbe0cbee805b2de4f6c00ef0/docs/tutorial/README.md#acquire-credentials-acquire-credentials)

**Comment by sirakc** [comment]
@nzjony I just went in and looked into the testing API key section, which gives API call url https://vector.hereapi.com/v2/vectortiles/base/mc/15/9646/12321/omv?apikey=
and I put my API key and it downloaded a blob into my PC, other than that I went and created my API key, funny thing I already did create my key but never used it cause it was a bit confusing back then now its more clear, thank you very much for that, 

1 feedback:
_After you sign up, you will me taken to a page which says "Project Details" on the left and "Get your credentials:" in the middle._
this line misses a section, After signing up or signing in, you see a list of projects first and then you have to click on one of them and that will open project details and you basically everything else from there

**Comment by sirakc** [comment]
@nzjony also it would be amazing to see a harp.gl React JS example, not just the code but the entire project as a github repo so that it becomes easy to see what file goes where

**Comment by nzjony** [comment]
@sirakc , thanks for the feedback! I will correct it.

We have an internal react js example, I will see if we can make it public... but not sure how difficult that is... will get back to you

**Comment by nzjony** [comment]
@sirakc , I just tried again with a throw away email and I get the following

<img width="1440" alt="Screenshot 2020-09-07 at 17 47 44" src="https://user-images.githubusercontent.com/2533428/92403879-ad842980-f132-11ea-89b1-f724a08d7a48.png">

I didn't see any list of projects.

I signed up here: https://developer.here.com/?create=Freemium-Basic

**Comment by nzjony** [comment]
@sirakc , the harp.gl react js examples we have are just undergoing a review and should hopefully be public soon!

**Comment by nzjony** [comment]
@sirakc , the tutorial is now up to date: https://developer.here.com/tutorials/harpgl/

So I will close this, thanks for the issue.
