### ISSUE TITLE
add GeoJsonDataSource on map view

### ISSUE THREAD

**Issue by marckwatney** [heremaps/harp.gl#1840]
I would like to display a geojson on the map but the problem is that the addDataSource method accepts only to receive the DataSource type and not the GeoJsonDataSource or other.

I followed this example : https://www.harp.gl/docs/master/doc/classes/harp_geojson_datasource.geojsondatasource-1.html

```
const geoJsonDataProvider = new GeoJsonDataProvider(
       "italy",
       new URL("resources/italy.json", window.location.href)
   );
   const geoJsonDataSource = new GeoJsonDataSource({
       dataProvider: geoJsonDataProvider,
       styleSetName: "geojson"
   });
   mapView.addDataSource(geoJsonDataSource); 
```

I have this error :
`Argument of type 'GeoJsonDataSource' is not assignable to parameter of type 'DataSource'.`

I don't understand how the method could accept other type of data like GeoJsonDataSource.

**Comment by nzjony** [comment]
@marckwatney , do you have the code available somewhere for me to take a look at ?

**Comment by marckwatney** [comment]
@nzjony Yes, here : https://github.com/marckwatney/harpgl-geojson

**Comment by nzjony** [comment]
@marckwatney , thank you. I took a look, your dependencies are not matching, i.e.:

        "@here/harp-geojson-datasource": "^0.19.0",
        "@here/harp-geoutils": "^0.17.2",

Run `npx npm-check-updates -u` to update them.

**Comment by nzjony** [comment]
@marckwatney , I guess you created this with the yeoman generator. It might pay to start from scratch.
