### ISSUE TITLE
Cannot use point geometry with dynamic property styling

### ISSUE THREAD

**Issue by J-Rojas** [heremaps/harp.gl#1873]
I'm attempting to use the dynamic properties feature to style geojson features dynamically. I've discovered that point geometry will not render correctly using the dynamic styling (ie applying a style if the enabled state changes dynamically). The cause of this is the lack of an index within the BufferGeometry for these rendered objects. The code skips over these (see line 4037 of MapView.ts) explicitly without applying the styling.

The easiest way to reproduce the bug is to modify the 'picking game' example and add a Point feature and duplicate the selection style, but instead use 'circles' as the technique.

Sample below:

```
    // add this to the italy.json "features" array...
   {
            "id": "BIGPOINT",
            "type": "Feature",
            "properties": {
                "id": 1,
                "area": 25394103941.6,
                "name": "piemonte",
                "density": 172,
                "height": 8600,
                "length": 1236869.3688,
                "@ns:com:here:xyz": {
                    "tags": [],
                    "space": "oDptvQ3E",
                    "createdAt": 1529933207139,
                    "updatedAt": 1529933207139
                }
            },
            "geometry": {
                "type": "Point",
                "coordinates": [8.449759643243958, 46.46176402906602]                        
            }
        },        

    // add this to the styles
    {
                description: "GeoJson points selection",
                when: ["==", ["geometry-type"], "Point"],
                renderOrder: 1010,
                technique: "circles",
                attr: {
                    // enable geometries created by this technique only when
                    // the feature's name is equal to the value stored
                    // in the dynamic property named `selected`
                    enabled: ["==", ["get", "name"], ["get", "selected", ["dynamic-properties"]]],

                    // select the color based on the the value of the dynamic property `correct`.
                    color: [
                        "case",
                        ["get", "correct", ["dynamic-properties"]],
                        "#009900",
                        "#ff4422"
                    ],

                    size: 100,

                    // avoid picking
                    transient: true
                }
    }
```

**Comment by nzjony** [comment]
@J-Rojas , thanks for reporting the issues. We have some internal users of harp.gl that have the exact same problem.

I will link the tickets, and we should fix this within the next 1/2 releases.

**Comment by nzjony** [comment]
@J-Rojas I fixed the issue with the index not being present on BufferGeometry: https://github.com/heremaps/harp.gl/commit/25c5ae4d41b989bbd1f3e65cd26c52724ce6140f. Can you try this again?

I tried it what you mentioned above locally and the red dot turned green when I clicked on the correct state.

**Comment by nzjony** [comment]
This is what I get:

<img width="396" alt="Screenshot 2020-10-15 at 15 34 01" src="https://user-images.githubusercontent.com/2533428/96136026-fb433d00-0efb-11eb-8007-14db280dcaed.png">
 
Then click:

<img width="440" alt="Screenshot 2020-10-15 at 15 34 45" src="https://user-images.githubusercontent.com/2533428/96136300-0c8c4980-0efc-11eb-8500-c91956a47769.png">

**Comment by nzjony** [comment]
I spoke too soon, I tried it actually without the fix, I had some repo and didn't check it was in the history. Will try again.

**Comment by nzjony** [comment]
Ok, maybe I have a fix, will try again tomorrow if it works. Seems to be because processTileObjectFeatures can't handle features without groups.

**Comment by nzjony** [comment]
It seems that the problem is with the: `if (start === endOfLastGroup) {` check, because the starts maybe undefined, then we would get if(undefined === undefined)... which would then access a non-existant group.
