### ISSUE TITLE
Add a threejs object that jiggles when the mouse scrolls

### ISSUE THREAD

**Issue by datouzhan** [heremaps/harp.gl#1897]
when I use the scroll wheel to move slowly, the scene will shake.This phenomenon only occurs on the additional threejs objects.
![shake](https://user-images.githubusercontent.com/20176393/95813580-c5128b80-0d4a-11eb-899d-a014367aa389.gif)

**Comment by nzjony** [comment]
@datouzhan , thanks for the issue. I think it has to do with not being updated before the render call. Do you set the camera's position in the `Render` callback?

**Comment by datouzhan** [comment]
I don't set the camera's position in the render callback.Just update map before the render call.how to set the camera's position in the Render callback?
![image](https://user-images.githubusercontent.com/20176393/95826087-64904800-0d64-11eb-995c-28c94a7895d2.png)

**Comment by nzjony** [comment]
@datouzhan , you mentioned: 

> This phenomenon only occurs on the additional threejs objects

How do you add this additional object to the scene? Do you use `MapAnchors` ?

**Comment by datouzhan** [comment]
yes,  i use MapAnchors
![image](https://user-images.githubusercontent.com/20176393/95932891-9c000280-0dff-11eb-9690-ae41acf658c9.png)

**Comment by nzjony** [comment]
@datouzhan , I've been looking into this, but I still don't know how it is possible.

In the `private render(frameStartTime: number): void` in `MapView.ts`, we, among other things:

1. call `updateCameras`
2. call `this.m_mapAnchors.update`
3. the render using the camera.

Are you by any chance using the `pointOfView` method and specifying some custom camera?

**Comment by datouzhan** [comment]
hi,@nzjony , thank you very much,i set overlay as false for the objects i add, they are in the same scene.it can resolve the reflaction problem.now it can reflect the ExtrudedPolygonTechnique buildings.But it is still shake.
![image](https://user-images.githubusercontent.com/20176393/96110385-613abf00-0f12-11eb-8021-615cef4173aa.png)
Should i call this.m_mapAnchors.update?

**Comment by datouzhan** [comment]
Hi,@nzjony ,thank you very much,i try to set the overlay as false for the objects i add, i resolve the problem of reflect the ExtrudedPolygonTechnique buildings.but it still  jiggle.
![image](https://user-images.githubusercontent.com/20176393/96111057-47e64280-0f13-11eb-90f0-01e71a1bbad0.png)
should i call this.m_mapAnchors.update?

**Comment by nzjony** [comment]
The `this.m_mapAnchors.update` is called internally, so you don't need to do it.

Glad you get the reflections working, looks good. The jiggle, I'm not sure, can you check that the position of the water in the `onBeforeRender` call in three.js is the same as that computed internally. I'm still puzzled why there is a difference?

If you can make some small demo showing the issue, I could also try to debug it.

**Comment by datouzhan** [comment]
hi @nzjony , i  check that the position of the water in the onBeforeRender call in three.js is the same as that computed internally .This phenomenon also occurs with other objects added via mapanchor, except for the model.So i will make some small demo showing the issue

**Comment by nzjony** [comment]
@datouzhan , very strange, ok thanks, yes a small demo to show the problem would help us identify the issue.

**Comment by datouzhan** [comment]
@nzjony ,yes,it is very strange.This is a small online demo,can you open it. https://codepen.io/datouzhan/pen/QWEEgwN

**Comment by datouzhan** [comment]
@nzjony ,hi,I found that my online example wouldn't open, so I updated it again

**Comment by nzjony** [comment]
@datouzhan , thank you, unfortunately I still get a blank screen:

![Uploading Screenshot 2020-10-22 at 14.11.43.png…]()

**Comment by datouzhan** [comment]
I confirmed once again that the example I tested locally was correct. Can I send you an example of my local test? Can you tell me the e-mail address?

**Comment by datouzhan** [comment]
hi, @nzjony ，I guess it is because the floating point number is too large that the precision is distorted.At present, the vertex coordinates are all in seven digits.

**Comment by FraukeF** [comment]
Hi @datouzhan,

As @nzjony  will be out of office for some weeks, I tried to open the codepen you created, to see the issue and hopefully be able to help. 

Unfortunately it throws soem errors regarding missing uniforms, if I add them (fogColor, fogNear, fogFar) it renders a map with some "blinking" lines but it does not match the screenshots...

If you have flickering, it might in deed be that there is precision issues. Maybe there is a way you can put your relative to the camera or some tile to decrease the size of the number?
