### ISSUE TITLE
the THREE obj add by mapAnchors has no influence in the map scene

### ISSUE THREAD

**Issue by aoyaZY** [heremaps/harp.gl#1901]
I add some three objects to map by mapAnchors , they only influence each other , but map obj.

Here is my map. The water and tall buildings are THREE objects , they were added by mapAnchors ,
but the water only reflect the tall buildings , can not reflect the ExtrudedPolygonTechnique buildings.
And the theme light only cast shadow on  the ExtrudedPolygonTechnique buildings , but not on THREE object buildings.
![image](https://user-images.githubusercontent.com/53169185/96099133-7ceb9880-0f05-11eb-8bf5-70e9316f91ac.png)

If map's objects and the custom THREE objects added by mapAnchors are in different scene?
How can I solve that ?

**Comment by nzjony** [comment]
@aoyaZY , thanks for creating the issue and using harp.gl, that is a pretty impressive demo you have!

Do you set `overlay` as `true` for the objects you add, otherwise they should be in the same scene as the other map objects? Or there is some bug on our side.

For the custom tall buildings, do you set `castShadow` to `true`, see: https://threejs.org/docs/#api/en/core/Object3D.castShadow

For the THREE.Water that you add, try setting the `styleSet` to `tilezen` and `category` to `water`, see: https://github.com/heremaps/harp.gl/blob/master/@here/harp-mapview/lib/MapAnchors.ts#L57 and https://github.com/heremaps/harp.gl/blob/master/@here/harp-mapview/lib/MapAnchors.ts#L66

At least these are required to compute the correct renderOrder for the objects, see: https://github.com/heremaps/harp.gl/blob/69af4d17600970a9653951e234716da6d1f0ac4b/%40here/harp-mapview/lib/MapAnchors.ts#L139

**Comment by aoyaZY** [comment]
@nzjony , nice ! You've been a great help to me , bro ! 
 Setting  overlay as false and suitable renderOrder has fixed the water problem.
![image](https://user-images.githubusercontent.com/53169185/96110708-d1e1db80-0f12-11eb-91c3-999469cb1170.png)

For the custom building's shadow , I have already set castShadow to true , but it doesn't work.

**Comment by nzjony** [comment]
@aoyaZY ,

Can you try using a `customDepthMaterial`, i.e. like:

```
    const alphaTest = 0.66;

    const customDepthMaterial = new THREE.MeshDepthMaterial({
        depthPacking: THREE.RGBADepthPacking,
        map,
        alphaTest
    });

    obj.customDepthMaterial = customDepthMaterial;
```

**Comment by nzjony** [comment]
where `obj` is the tall buildings. Does that help?

**Comment by aoyaZY** [comment]
@nzjony , 
the tall buildings are FBX , I have tried turn it to OBJ format too , but the problem is still there
![image](https://user-images.githubusercontent.com/53169185/96206850-65132380-0f9c-11eb-8c57-03aef42e1180.png)
![Uploading image.png…]()

**Comment by aoyaZY** [comment]
@nzjony 
the tall buildings are FBX , I have tried turn it to OBJ format too , but the problem is still there
![image](https://user-images.githubusercontent.com/53169185/96207068-e36fc580-0f9c-11eb-866b-37d5500f2359.png)
![image](https://user-images.githubusercontent.com/53169185/96207091-f2ef0e80-0f9c-11eb-873e-0a07a5036848.png)

**Comment by nzjony** [comment]
@aoyaZY , when I mentioned `obj`, I didn't mean the format, I meant it was reference to some object.

In `objloader.load` method, before the `map.mapAnchors.add(object)` add:

```
obj. customDepthMaterial  = new THREE.MeshDepthMaterial({
        depthPacking: THREE.RGBADepthPacking
    });
```

**Comment by aoyaZY** [comment]
Unfortunately , I have tried , but failed  T_T

**Comment by nzjony** [comment]
@aoyaZY , I recommend you try the https://threejs.org/examples/webgl_shadowmap_viewer.html, so you can debug if the buildings are in the shadow map.

See also: https://github.com/heremaps/harp.gl/blob/jsminor161020/@here/harp-examples/src/threejs_shadows.ts

If you want to run the demo, simply check out the branch `jsminor161020`, then run `yarn && yarn start`, go to local host and run the "shadows", example.

**Comment by nzjony** [comment]
This is what the `threejs_shadows.ts` example looks like:
<img width="1277" alt="Screenshot 2020-10-16 at 13 59 27" src="https://user-images.githubusercontent.com/2533428/96255857-e88e3e00-0fb7-11eb-9f69-e860645522a8.png">

**Comment by aoyaZY** [comment]
@nzjony , sorry to get back to you so late
 I found that loaders is the key to this question. FBXLoader or OBJLoader loads model as Group , not Object3D.
Setting the group's castShadow as true is useless , so I need to travel group's children and set their castShadow as true.
Now it is working , thank for your help !
![image](https://user-images.githubusercontent.com/53169185/96554853-a7fd3000-12e9-11eb-91c4-7ed4b90c0d80.png)

**Comment by nzjony** [comment]
@aoyaZY , thanks for the update, glad you figured it out!
