### ISSUE TITLE
Does harp  contain THREE post-processing?

### ISSUE THREAD

**Issue by aoyaZY** [heremaps/harp.gl#1911]
Hey bro , Does harp  contain THREE's post-processing?  How can I use it?
![image](https://user-images.githubusercontent.com/53169185/96823170-70fc5b00-145e-11eb-8070-60221b1e693d.png)

**Comment by nzjony** [comment]
@aoyaZY , check out:

https://www.harp.gl/docs/master/examples/#rendering_post-effects_all.html

https://www.harp.gl/docs/master/examples/#rendering_post-effects_themes.html

**Comment by aoyaZY** [comment]
@nzjony ,thanks
I've seen those example before , those are about the whole scene or theme post-processing
I am trying to make custom Object's effects , like single building bloom or something
so I need some module like EffectComposer,RenderPass and so on , just like what THREE‘s’ doc said: https://threejs.org/docs/index.html#manual/en/introduction/How-to-use-post-processing
Does harp contain these module? Or I need to import by myself ?

**Comment by Astrak** [comment]
Hard coding the effects in the code was first imagined to quickly benefit the threejs rendering possibilities. However it does not allow generation of custom effects, an API would need to be design in that purpose, which would be more reasonable and maintainable as well. It was first planned for demoing and was surely not the most consensual idea.

**Comment by nzjony** [comment]
@aoyaZY , I'm not quite sure I follow, my understanding of post-processing is that it applies some processing to the currently rendered output, so if you wanted some single building / object bloom, you would need to render it separately and then overlay it on the scene. Is that what you mean?

Yes, as mentioned by @Astrak , what we have would need to be extended to make it more customizable, we had another request to add this, see: https://github.com/heremaps/harp.gl/issues/1561

I will ask internally if we can raise the priority to add such an API to expose the EffectComposer etc.

**Comment by nzjony** [comment]
@aoyaZY , do you mean something like: https://threejs.org/examples/?q=post#webgl_postprocessing_unreal_bloom_selective ?

Or is there another three.js demo which shows what you want to achieve?

**Comment by nzjony** [comment]
@aoyaZY , we found a ticket that @Astrak  had created a while back to add this API, I have linked it.

**Comment by Astrak** [comment]
I actually remember a request for such a thing as highlighting a road or a building at the time of the implementation of the post processing. However I think it was not possible to determine the semantics of the result of the raycasting (a building can be several polygons, like for the ones in NY). I don't remember what data this applied to though, and if it could now be possible.

**Comment by nzjony** [comment]
@Astrak, I think for buildings it would unfortunably not be possible, at least there is no unique ids generated for the buildings in the data that I am currently aware of. Unless the buildings were somehow ID'ed by location. For roads, I guess you have the same problem. BTW, have you seen: https://www.harp.gl/docs/master/examples/#object-picking.html ? It at least shows picking of roads is possible.

**Comment by aoyaZY** [comment]
@nzjony ,  yes , that's the example I have seen , you do know what I'm talking about .
And I know what you're going through , good luck !
I will try MapRenderingManager , thanks !

**Comment by nzjony** [comment]
@aoyaZY , thanks. All the best and let us know how you get on. Either re open this issue or create a new one if you have problems / need help.
