### ISSUE TITLE
React.js example for Harp.gl

### ISSUE THREAD

**Issue by sirakc** [heremaps/harp.gl#1935]
hey! :) I think this is already done but I am unaware of the status, so I am asking again if the harp.gl has a downloadable example based on React.js? I asked for this some weeks ago, at least more than a month and I don't know where to find the react example or if there is one, if there is, that would be great and also great job on the new documentation and guide

**Comment by nzjony** [comment]
hey @sirakc , we have it, but it is not yet ready to be officially released, sorry about that. Hopefully we can make some progress soon, however we have a lot of internal work, so it may be slow unfortunately.

In the mean time, have you seen: https://github.com/slaylines/harp.gl-react-example ?
