### ISSUE TITLE
Roadmap / 3D terrain

### ISSUE THREAD

**Issue by vicb** [heremaps/harp.gl#1950]
I haven't been able to find a roadmap for the project.
Is there one available somewhere ? 
And if no, do you plan to add one ?

One feature I am actually interested in is 3D terrain (relief) rendering.
Do you have any plan for that ?

What about adding a comparison with other rendering engine like Cesium and iTowns (both open source) or Arcgis and mapbox (closed source). It would be great to have a high level overview of the features supported by those different platforms.

This project looks very promising.
Thanks for your hard work and publishing it as open source !

**Comment by nzjony** [comment]
Hey @vicb , thanks for the questions!

Yeah, we have terrain working internally within our company, actually if you search for "Terrain", there are 150 results, however the service to give the tile data isn't yet ready for public use, and I'm not sure exactly when it is. I'll ask internally if someone can comment.

A comparison with other engines makes sense for sure! We still have a bit of a way to go to reach feature parity, as harp.gl is still heavily in development, so I don't think we would do it just yet, but maybe in 6 - 12 months, I can see it making sense.

Your welcome!

**Comment by vicb** [comment]
Thanks a lot for your helpful answer Jonathan !

I had done that search for terrain and also found https://github.com/heremaps/harp-terrain-datasource but I was not sure about the exact status. Thanks for clarifying.

> but maybe in 6 - 12 months [...]

I think this gives a sense on when harp.gl will be "ready". That's great.

Keep up the good work !
