### ISSUE TITLE
text for polygon

### ISSUE THREAD

**Issue by aoyaZY** [heremaps/harp.gl#1951]
Is there any text technique for polygon ? 
Just like  LineMarkerTechnique for polyline ， is there PolygonMarkerTechnique or something to mark inside polygon ?
For example , I want to mark out blocks or countrise , but I only have polygon data

**Comment by nzjony** [comment]
@aoyaZY , thanks for the issue. I have created an internal ticket so that we can track this. Hopefully we can look at implementing it soon. Or if you want, feel free to open a PR.

**Comment by nzjony** [comment]
@aoyaZY. I asked internally and there was some confusion about what exactly you want, I took it to mean that you want to add some text at the center point of the polygon? Or do you mean something different?

**Comment by aoyaZY** [comment]
@nzjony , yes , center point
But I just found out it's better if text can be spread out across the polygon , and we can define their spacing
because there might be a long river that we want to mark out , if the text only added at the polygon center , we can not see it the rest part .
So , maybe we can design it like this:
Text is spread out across the polygon start from center point and can be define spacing.
In this way , the text only show at the center point if the polygon just can contain one text
Just a suggestion : )
And there is the effect on mapbox , maybe it will give your team a little inspiration
![image](https://user-images.githubusercontent.com/53169185/98324903-8067d080-2028-11eb-8edf-94a92a2b322a.png)

**Comment by nzjony** [comment]
@aoyaZY , thanks for clarifying, however I unfortunately don't quite understand what you mean by spacing, do you mean that the name is repeated multiple times? Maybe you can give some simple examples like with a square, rectangle, concave shape etc to help me better understand.

Regarding the image, I don't quite understand what you are trying to point out, what is special about the labels in the red box? Are they using some sort of text technique for polygons? Also, where are the tile boundaries?

**Comment by aoyaZY** [comment]
@nzjony , sorry for confusing you : (
![image](https://user-images.githubusercontent.com/53169185/98341133-5b378a00-2049-11eb-9574-fd87188ff865.png)

As the image shows , the river as you see is a complete geometry , the text is its name. 
Spacing means the space between two text.
![image](https://user-images.githubusercontent.com/53169185/98344129-c08d7a00-204d-11eb-8b6e-61c5c94ea435.png)

**Comment by nzjony** [comment]
Ok, thank you @aoyaZY  for clarifying.
