### ISSUE TITLE
feature selection expressions

### ISSUE THREAD

**Issue by aoyaZY** [heremaps/harp.gl#1961]
Is there any feature selection expression about "slice"?
just like this : [url](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#slice)

**Comment by nzjony** [comment]
I can't see it in our [documentation](https://github.com/heremaps/harp.gl/blob/master/@here/harp-datasource-protocol/StyleExpressions.md)

@robertoraggi , do you know if we plan to support this operator?

**Comment by robertoraggi** [comment]
No, we don't have it yet, but we could add it. I will do it next week.

**Comment by aoyaZY** [comment]
@robertoraggi thanks , bro

**Comment by robertoraggi** [comment]
The PR was merged.
