### ISSUE TITLE
Red Theme

### ISSUE THREAD

**Issue by rlkelly** [heremaps/harp.gl#1970]
I'd like to get this theme: https://developer.here.com/tutorials/harpgl/img/background.png .  It's very visually appealing and I'm having a hard time recreating it.

**Comment by nzjony** [comment]
@rlkelly , thanks for the issue. I'll ask around in the team if anyone knows.

**Comment by nzjony** [comment]
@rlkelly , see: https://github.com/heremaps/harp.gl/pull/1975/files

I took the `berlin_tilezen_effects_streets.json` as inspiration and tweaked it a little bit from a style given to me by @devallois.

We will however try to release the full style, but it may need a week or so to get it approved etc.
