### ISSUE TITLE
Is there any datasource not display like tile?

### ISSUE THREAD

**Issue by aoyaZY** [heremaps/harp.gl#1976]
Hi , it's me again
I found that features-datasource and geojson-datasource both are VectorTileDataSource , they would load data tile by tile , 
especially when I zoom the map , that would be quite obvious
![image](https://user-images.githubusercontent.com/53169185/99480108-687e3e00-2992-11eb-911d-762858567658.png)
![image](https://user-images.githubusercontent.com/53169185/99493943-201f4a00-29ab-11eb-8fb5-7060a39dca21.png)
Is there any class or interface can add data to map directly and don't split it tile by tile ? I hope show some features completely ， 
even though it take more time

**Comment by nzjony** [comment]
We have the idea of a `mapAnchor`, see; https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fthreejs_add-object.ts

If you have some mesh, you can anchor it at some lat/long coordinate and it will be centered there, you could have an object much larger than a tile and you wouldn't get any splitting.

Does that help? Or do you have a more specific use case?

**Comment by nzjony** [comment]
@aoyaZY , btw, your app looks impressive! I look forward to see it soon.

**Comment by aoyaZY** [comment]
Yes , maybe mapAnchor is the only way for me 
My data is geojson format , it contains many large features , I just want to add it conveniently like traditional 2D map API and don't get any splitting. But it seems impossible , so I will use mapAnchor ,thanks 
Btw , the app not yet completed , but I can give you a glance  : )
![image](https://user-images.githubusercontent.com/53169185/99502248-c4a78900-29b7-11eb-9f10-231c5aadca43.png)

**Comment by nzjony** [comment]
@aoyaZY , wow, that looks impressive!

I wonder, have you tried playing with the minDataLevel / maxDataLevel, could you find the tile that fits the data completely?

**Comment by aoyaZY** [comment]
@nzjony , yes , I can control tile data request by that now , thanks

**Comment by aoyaZY** [comment]
@nzjony , yes , I can control tile data request by that now , thanks
