### ISSUE TITLE
Satellite Tiles not displayed with (HereTileProvider, HereWebTileDataSource)

### ISSUE THREAD

**Issue by PanetoneCake** [heremaps/harp.gl#1995]
**Describe the bug**
I try to display Satellite tiles on the GlobeMap (HarpGL)
When i pushed my code i had no error but nothing displayed on the Globe (Look Sample 1 after)

It work with (**OmvDataSource**) but not with (**HereWebTileDataSource**)
<img width="1665" alt="capture_d___e__cran_2020-11-28_a___14 02 59" src="https://user-images.githubusercontent.com/73563799/100516262-f91f0000-3182-11eb-8638-d3a23cc9de91.png">

I Have this result with (**HereWebTileDataSource**)
<img width="603" alt="Capture d’écran 2020-11-28 à 14 08 47" src="https://user-images.githubusercontent.com/73563799/100516309-3f745f00-3183-11eb-88f7-6e6c426fb6f1.png">

and this result with  (**OmvDataSource**) :
<img width="602" alt="Capture d’écran 2020-11-28 à 14 10 53" src="https://user-images.githubusercontent.com/73563799/100516340-8a8e7200-3183-11eb-8778-97d29288c6d6.png">
**MY CODE **

```
 const dataSource = new HereWebTileDataSource({ authenticationCode: process.env.REACT_APP_HERE_APIKEY , 
 tileBaseAddress: HereTileProvider.TILE_AERIAL_SATELLITE});
 map.addDataSource(dataSource)
```

**Comment by PanetoneCake** [comment]
I ve this now (I updated this line: `mapView.addDataSource(webTileDataSource)` like Earth Harp Sample.
[https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fdatasource_satellite-tile.ts](url)

Same result .No return for Satellite tiles.

<img width="783" alt="Capture d’écran 2020-11-29 à 10 38 04" src="https://user-images.githubusercontent.com/73563799/100538259-f8dc3e80-322e-11eb-9b64-7bb58841adf7.png">
<img width="1351" alt="Capture d’écran 2020-11-29 à 10 39 03" src="https://user-images.githubusercontent.com/73563799/100538297-29bc7380-322f-11eb-9331-246ee9d42af2.png">
<img width="1393" alt="Capture d’écran 2020-11-29 à 10 42 29" src="https://user-images.githubusercontent.com/73563799/100538361-96377280-322f-11eb-8e3e-20e3c9b4a3d5.png">

**Comment by FraukeF** [comment]
Hello @PanetoneCake , 

I am sorry you are having issues reproducing this example. 
From your code, as far as I can see, everything looks fine. The errors you posted are strange, as for the first one I actually see in you example that you pass options to MapView, so it shouldn´t be undefined. Do you have a stacktrace for that, to maybe better see, how options could become undefined?
 The second error points to a line in the code, where there is only a comment, so I guess, that maybe the sourcemaps dont match?

Regarding the satellite tiles, could you check what response you get from the network for the requests of the satellite tiles?
The url should look something like: "https://1.aerial.maps.ls.hereapi.com/maptile/2.1/maptile/newest/satellite.day/4/8/6/512/png8?apikey=${your-api-key} "

Frauke

**Comment by PanetoneCake** [comment]
Hi @FraukeF 
Thank for your feedback
For url : 
"https://1.aerial.maps.ls.hereapi.com/maptile/2.1/maptile/newest/satellite.day/4/8/6/512/png8?apikey=${your-api-key} "
when i test it _**manualy**_ , i have this : 
<img width="1651" alt="Capture d’écran 2020-11-30 à 09 09 34" src="https://user-images.githubusercontent.com/73563799/100583985-c6dce200-32eb-11eb-89dc-f5275be5ab31.png">

For **_stacktrace_** i have this but  I don't understand well the diagnostic : 
<img width="1678" alt="Capture d’écran 2020-11-30 à 09 46 05" src="https://user-images.githubusercontent.com/73563799/100587460-e1658a00-32f0-11eb-8fec-7800744fa088.png">
<img width="1680" alt="Capture d’écran 2020-11-30 à 09 54 18" src="https://user-images.githubusercontent.com/73563799/100588332-060e3180-32f2-11eb-9398-0111d5655fdb.png">
<img width="1680" alt="Capture d’écran 2020-11-30 à 09 54 50" src="https://user-images.githubusercontent.com/73563799/100588421-19210180-32f2-11eb-97b1-5c30170a3a16.png">

**Comment by PanetoneCake** [comment]
I tried again whith "map" instead "mapView"  i could see this in ConsoleLog : 
<img width="1680" alt="Capture d’écran 2020-11-30 à 11 38 11" src="https://user-images.githubusercontent.com/73563799/100599622-89cf1a80-3300-11eb-89a8-894798b1b114.png">

& I have empty Globe 
<img width="600" alt="Capture d’écran 2020-11-30 à 11 39 46" src="https://user-images.githubusercontent.com/73563799/100599796-c1d65d80-3300-11eb-872e-650e700bda3c.png">

**Comment by PanetoneCake** [comment]
@FraukeF  I saw this also in the report . Visibly it failed to load tiles :
<img width="1679" alt="Capture d’écran 2020-11-30 à 12 14 50" src="https://user-images.githubusercontent.com/73563799/100603613-a883e000-3305-11eb-8468-7e2e82ab78ed.png">
<img width="1680" alt="Capture d’écran 2020-11-30 à 12 13 29" src="https://user-images.githubusercontent.com/73563799/100603487-783c4180-3305-11eb-8699-2537fe4e7513.png">

**Comment by FraukeF** [comment]
Hi @PanetoneCake 

this looks indeed as if the loading of tile does not work, .. can you check in your network tab in your browser what responses you get for the satellite tiles

**Comment by PanetoneCake** [comment]
I ve this : 
<img width="1680" alt="Capture d’écran 2020-11-30 à 13 08 08" src="https://user-images.githubusercontent.com/73563799/100608951-842c0180-330d-11eb-845a-46e28f438ce5.png">
<img width="1680" alt="Capture d’écran 2020-11-30 à 13 08 30" src="https://user-images.githubusercontent.com/73563799/100608961-87bf8880-330d-11eb-8e0a-151db6477d36.png">
<img width="1680" alt="Capture d’écran 2020-11-30 à 13 09 53" src="https://user-images.githubusercontent.com/73563799/100608974-8d1cd300-330d-11eb-842e-b16ee9de1bff.png">
(**When i click on PNG8**)
<img width="1680" alt="Capture d’écran 2020-11-30 à 13 10 00" src="https://user-images.githubusercontent.com/73563799/100608858-5d6dcb00-330d-11eb-834b-b47d51094a18.png">

**Comment by FraukeF** [comment]
@PanetoneCake 
You are getting a "401" for the tile request, which means your authentication fails. Seeing the request that is fired, this is caused by the missing "apiKey" query parameter.

In your code, please make sure to pass <your-api-key> here:

  const webTileDataSource = new HereWebTileDataSource({
        apikey: <your-api-key>,
        tileBaseAddress: HereTileProvider.TILE_AERIAL_SATELLITE
    });


I see, that currently you are passing it as "authenticationCode" which is used for bearerToken authentication...

**Comment by PanetoneCake** [comment]
Thank you very much @FraukeF 
It work well now 👍🏽
<img width="823" alt="Capture d’écran 2020-12-01 à 12 37 27" src="https://user-images.githubusercontent.com/73563799/100735726-fb2ace00-33d1-11eb-8414-2a91c1fdec6c.png">

**Comment by FraukeF** [comment]
@PanetoneCake great to hear, that it works now. Glad I could help.
