### ISSUE TITLE
Some tiles missing at resolutions around 5K and greater

### ISSUE THREAD

**Issue by brent-williams** [heremaps/harp.gl#2057]
**Describe the bug**

Tiles are not rendered at resolutions >= around 5K.

**To Reproduce**

1. Set screen resolution to 5K or larger on supporting hardware (on macOS, System Preferences | Display | (hold option button and click) Scaled | select resolution).
2. Cover desktop with browser
3. Run any harp.gl example including flat projection, sphere projection with or without tilt, vector or raster.
4. Tiles are missing around all four edges of the screen for sphere projection and at the bottom-right for mercator projection. 

**Expected behavior**

Tiles not missing.  Using offscreen rendering I've found the problem is even more pronounced (=more missing tiles) at higher resolutions e.g. 8K.  I don't see failed tiles in the network tab suggesting maybe a bug in tile visibility calculations.

**Desktop (please complete the following information):**

- OS: macOS Catalina 10.15.6
- Browser: Chrome and Chromium latest
- Version: master

**Screenshots**

![5k_flat](https://user-images.githubusercontent.com/1694687/104839386-73127080-590c-11eb-9055-5d162e53cdd0.png)
![5K_sphere](https://user-images.githubusercontent.com/1694687/104839387-7f96c900-590c-11eb-9ed4-f500293a6e76.png)

**Comment by FraukeF** [comment]
Hi @brent-williams,

harp.gl per default runs with a maximum visible tile count of 100, for performance purposes.
You can tweak this, using the MapViewOptions by passing the maxVisibleDataSourceTiles (https://www.harp.gl/docs/master/doc/interfaces/harp_mapview.mapviewoptions-1.html#maxvisibledatasourcetiles)  property with a higher value, be aware that this might cause a performance drop.

**Comment by brent-williams** [comment]
Confirmed maxVisibleDataSourceTiles addresses the issue thanks for the very quick turnaround.
