### ISSUE TITLE
Uncaught TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by degatt2** [heremaps/harp.gl#2114]
**Describe the bug**
Following the code of "Bundle Example", give me the following error:
**Uncaught TypeError: Right-hand side of 'instanceof' is not an object**

**To Reproduce**
1. Copy & paste the code from: https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fgetting-started_hello-world_js-bundle.html
1. Change your ApiKey
2. Run!
4. See error in console

**Additional context**

**Comment by FraukeF** [comment]
Hi @degatt2 ,

I saw, that you had a conversation with @robertoraggi  regarding this issue, did you find a solution?

**Comment by degatt2** [comment]
Yes, I did. It was an cache issue. restarted the computer and server, and error disappeared.
