### ISSUE TITLE
Error - vectorTileDataset.setStyleSet(styles); not a function - Following Harp.GL tutorial on HERE Dev Portal

### ISSUE THREAD

**Issue by cpandit201** [heremaps/harp.gl#2136]
I am following tutorial posted on HERE Developer portal 
https://developer.here.com/tutorials/harpgl/#introduction

Currently was on step to add remote data on map to style 
https://developer.here.com/tutorials/harpgl/#add-data-to-the-map

```

// At the bottom of index.ts
async function addRailRoads() {
    const globalRailroads = new VectorTileDataSource({
        baseUrl: "https://xyz.api.here.com/hub/spaces/hUJ4ZHJR/tile/web",
        apiFormat: APIFormat.XYZSpace,
        authenticationCode: 'ACbs-cqcFI4FlPRLK_VF1co', //Use this token!
    });

    await mapView.addDataSource(globalRailroads);
    const styles = [
        {
            when: ["==", ["geometry-type"], "LineString"],
            renderOrder: 1000,
            technique: "solid-line",
            color: "#D73060",
            opacity: 1,
            metricUnit: "Pixel",
            lineWidth: 1,
        }
    ];
    globalRailroads.setStyleSet(styles);
    mapView.update();
}
addRailRoads();
```

However I am getting the error on last third line
```
    globalRailroads.setStyleSet(styles);
index.js:106 Uncaught (in promise) TypeError: globalRailroads.setStyleSet is not a function
    at addRailRoads (index.js:106)
```

PFB Screenshot 
![image](https://user-images.githubusercontent.com/42322819/110160732-67263380-7e12-11eb-8c5e-0ae70ed8d3d0.png)

**Comment by nzjony** [comment]
Thanks @cpandit201  for the bug report and finding an issue in the tutorial!! I will fix it ASAP

**Comment by FraukeF** [comment]
@cpandit201  you can use `globalRailroads.setTheme(styles);` in the mean time

**Comment by nzjony** [comment]
@cpandit201 , thanks for your patience. It is now up to date, please see: https://developer.here.com/tutorials/harpgl/#further-examples
