### ISSUE TITLE
Slack join link expired

### ISSUE THREAD

**Issue by mvexel** [heremaps/harp.gl#2157]
**Describe the bug**
Clicking on "harp.gl Slack channel Registration available here" leads to a page that says: "This link is no longer active"

**To Reproduce**
See above

**Expected behavior**
reach an invite page that lets you join

**Comment by nzjony** [comment]
@mvexel , please try: https://join.slack.com/t/heredev/shared_invite/zt-nix6y5fb-WPQwpFlxZs1P4EJWhkrT9Q

I'll add a calendar reminder to manually update it so I don't forget.
