### ISSUE TITLE
Poly Features flicker / distort on zooming

### ISSUE THREAD

**Issue by mvexel** [heremaps/harp.gl#2158]
**Describe the bug**
Poly Features flicker / distort on zooming

**To Reproduce**
1. Go to [the example project](https://www.harp.gl/docs/master/examples/#getting-started_globe-projection.html) with Firefox 86
2. Find an area that has plenty of building footprints
3. Zoom in / out using mouse wheel

**Expected behavior**
Smooth scrolling and consistent display of features 

**Screenshots**
![Screen Recording 2021-03-26 at 8 30 57 AM(1)](https://user-images.githubusercontent.com/120452/112648031-b60e2a00-8e0e-11eb-9b12-328b3e1792a5.gif)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Firefox 86

**Comment by nzjony** [comment]
@mvexel , thank you! We will look into a fix soon.
