### ISSUE TITLE
Does harp.gl support altitude for points and lines?

### ISSUE THREAD

**Issue by JNBarnes** [heremaps/harp.gl#2175]
Hi Folks, 

I've had a read through the docs and played with the examples. 

I cannot seem to render lines and points with an altitude.

I have tried to supply altitude as a 3rd parameter for each point, and as a property.

`{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
            "text":"Test",
            "altitude":1500.0
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               -0.468552,
               51.466060999999996,
               1500.0
            ]
         }
      }
   ]
}`

From what I have seen so far, this does not appear to be rendered, i.e. all points seem to render at the same height relative to the surface of the earth.

Am I doing it incorrectly, or is this a feature that is not currently supported?

If it is supported, I'd appreciate a nudge in the right direction!

I'm aware of the label offset, but I do not believe that is appropriate for my specific use case.

I'm attempting to render some long fairly dense tracks (lines) in 3d  geo-space. Ideally the lines would be interactable (the user can click on them).

I think it would be possible to bodge something together by manually creating a mesh in three.js and importing that model, but I would prefer to use the point/line API if it supports what I am trying to do.

Thank you.

**Comment by nzjony** [comment]
hi @JNBarnes , thanks for creating the issue.

We do currently support points with an altitude, see: https://www.harp.gl/docs/master/examples/#datasource_geojson_elevated-markers.html and the code: https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fdatasource_geojson_elevated-markers.ts

But unfortunately not lines or polygons, we have two internal tasks which I have linked as labels.

I'll let our PO know and see if we can raise the priority for this.

**Comment by nzjony** [comment]
Added links which point to internal jira tickets.

**Comment by nzjony** [comment]
@JNBarnes , I asked internally, but unfortunately we don't have the capacity to look into this just yet. I guess however in 4-6 months we could have some capacity to fix this issue.

Yes, you could create the lines using three.js and just pass them to us using the `mapAnchors` API, this is a very simple example: https://www.harp.gl/docs/master/examples/#threejs_add-object.html

**Comment by JNBarnes** [comment]
Hello, thanks for the response.

In the short term I think we'll have to go with a different library, but I'll keep an eye on this project. 

You've done a fantastic job, I'm excited to see where it goes!

**Comment by nzjony** [comment]
thanks @JNBarnes !!
