### ISSUE TITLE
Line caps not showing

### ISSUE THREAD

**Issue by mbob001** [heremaps/harp.gl#2197]
**Describe the bug**
I defined style for solid-line with caps. But caps not showing in map.

**To Reproduce**
1. Define style for solid-line
`styles: {
                history: [                  
                    {
                        technique: "solid-line",
                        renderOrder: 10002,
                        attr: {
                            color: "#09f",
                            lineWidth: 2,
                            metricUnit: "Pixel",
                            caps: "Square",
                        }
                    }
                ]
            }`
2. Add feature one line with more points
` let points = [];
        for (var i = 0; i < data.length; i++) {                
            points.push([data[i].Longitude, data[i].Latitude]);
        }

        
        let lines = new harp.MapViewLineFeature(points, {
            name: "history"
        });
        let historySource = new harp.FeaturesDataSource({
            name: "history",
            styleSetName: "history",            
            features: [lines]
        });
        this.map3D.addDataSource(historySource);`

**Expected behavior**
I expect line with start or end with caps or caps for each point.

**Screenshots**
No caps :(
![nocaps](https://user-images.githubusercontent.com/26133350/118617285-c44f4580-b7c2-11eb-99be-fc01ab4fd236.PNG)

**Additional context**
My target is to show arrows of direction line.

Thanks.

**Comment by nzjony** [comment]
@mbob001 , thank you. Let me take a look and I'll get back to you

**Comment by nzjony** [comment]
@mbob001 , I took another look at the line, it looks ilke it is using a square cap, see attached image: 
<img width="526" alt="Screenshot 2021-05-18 at 12 45 07" src="https://user-images.githubusercontent.com/2533428/118638291-fa96c000-b7d6-11eb-85f5-a7341a7eb00f.png">

Can you please increase the line width to say 40 and show me the result?

**Comment by mbob001** [comment]
Here it is.
![nocaps2](https://user-images.githubusercontent.com/26133350/118639648-6af21100-b7d8-11eb-9c0c-b9c126f7e352.PNG)

![nocaps3](https://user-images.githubusercontent.com/26133350/118639679-6fb6c500-b7d8-11eb-9367-297243fe5abf.PNG)

**Comment by nzjony** [comment]
Ok, looks good, should I close the issue?

**Comment by mbob001** [comment]
So, caps mean line is drawed by the value? In this example as a sqaure brush?
How can draw points of line as circle or schuare, see picture.
![nocaps](https://user-images.githubusercontent.com/26133350/118641407-67f82000-b7da-11eb-940f-553085abcd21.PNG)

Do I have to insert new features as points?
Thanks.

**Comment by nzjony** [comment]
The caps just means how the line ends are rendered, for example, square caps look like:

![webglrenderer-solid-lines-caps-square-20px current](https://user-images.githubusercontent.com/2533428/118641693-c0c7b880-b7da-11eb-9d30-1481d8ce9601.png)

Circle caps look like:

![webglrenderer-solid-lines-caps-round-20px current](https://user-images.githubusercontent.com/2533428/118641736-d0470180-b7da-11eb-9653-8621351ba652.png)

**Comment by nzjony** [comment]
Ahh ok, I see what you want. 

Have you tried: https://www.harp.gl/docs/master/examples/#styling_square-technique.html ?

I.e. using `technique:squares` or `technique:circles` ?

**Comment by mbob001** [comment]
I am looking for something like that:
[https://openlayers.org/en/latest/examples/line-arrows.html](url)

**Comment by nzjony** [comment]
We have an example here: http://localhost:8080/#markers_dynamic.html

Which dynamically adds markers using the MapViewPointFeature... but I don't know how to specify the direction. @atomicsulfate , do you know?

**Comment by mbob001** [comment]
Yes, I know that. I think I have to calculate direction from the lines and then draw arrows as a points.
Thanks.

**Comment by nzjony** [comment]
Yes, calculating the direction is ok, I just don't know how to pass the direction to the marker so that it can be rotated.

**Comment by nzjony** [comment]
@mbob001, I asked internally, such a feature isn't available yet unfortunately.

**Comment by mbob001** [comment]
Ok, thanks for your help.
