### ISSUE TITLE
ExtrudedLineTechnique

### ISSUE THREAD

**Issue by aoyaZY** [heremaps/harp.gl#2204]
I have try to make polygon's borderline clearly by lineWidth , but it didn't work by **extruded-line** .
**fill** or **extruded-polygon** is ok, however their lineWidth is limited to the [0, 1] range.
Can you give a simple example about **ExtrudedLineTechniqueParams** ?

**Comment by nzjony** [comment]
I tried `lineWidth`, but it seems to be broken, at least it was only showing a single pixel outline, i.e. with the following style:

```
when: ["==", ["geometry-type"], "Polygon"],
technique: "fill",
renderOrder: 100000,
attr: {
        color: ["get", "color"],
        lineColor: "#f00",
        lineWidth: 15
}
```

I get the following image (it looks thicker than 1px, but on my screen, it is 1px).
<img width="795" alt="Screenshot 2021-05-25 at 11 42 39" src="https://user-images.githubusercontent.com/2533428/119476579-77351b80-bd4e-11eb-8a1b-41a2a12bb973.png">

If you want a polygon outline, you can just define two steps:

```
{
    when: ["==", ["geometry-type"], "Polygon"],
    technique: "fill",
    renderOrder: 100000,
    attr: {
         color: ["get", "color"]
    }
},
{
    when: ["==", ["geometry-type"], "Polygon"],
    technique: "solid-line",
    renderOrder: 100100,
    attr: {
        color: "#000",
        lineWidth: "2px"
    }
}
```

And that gives: 
<img width="868" alt="Screenshot 2021-05-25 at 11 42 45" src="https://user-images.githubusercontent.com/2533428/119476986-e0b52a00-bd4e-11eb-87d7-6e07405a0756.png">

Would that suit for now @aoyaZY ?

**Comment by aoyaZY** [comment]
@nzjony thank you ,that's helpful.
