### ISSUE TITLE
Upgrade agent-base package to latest v6.0.2 to fix http proxy issue [ERR_INVALID_PROTOCOL]

### ISSUE THREAD

**Issue by drametoid** [heremaps/harp.gl#2208]
**Describe the bug**
When trying to do `yarn install` behind a http proxy, installation fails giving `[ERR_INVALID_PROTOCOL]`. First at installation of `geckodriver` package but workaround for that is to set correct proxies in env variable `proxy` and `https-proxy` for yarn and npm and to unset env variables `http_proxy https_proxy` (for capital case too). 
However, even after that, I'm getting an error with installation of puppeeteer. 
Investigated further and it seems that it has to do with an issue in the `agent-base` version used in harp.gl. Latest for the package is v6.0.2 whereas harp uses 6.0.1. 

This exact issue has been fixed in their latest version. See [PR 47](https://github.com/TooTallNate/node-agent-base/pull/47).

I can't seem to update it manually due to upstream dependency conflicts.

**To Reproduce**
1. Set yarn and npm proxy env vars `proxy = http://...` and `https-proxy = http://...`
2. Try `yarn install` behind these proxies.
3. Main issue is with accessing https URLs with http proxies.
NOTE: I have tried this inside docker environment.

**Expected behavior**
Successful installation of harp.gl package using yarn install command.

**Screenshots**
See error logs [here](https://www.pastebin.com/SPeS6L2a)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 inside Docker
 - Version: 
 a) npm v7.14.0
 b) node v16.2.0
 
 EDIT:
 **For reference**
 [Agent-base PR](https://github.com/TooTallNate/node-agent-base/pull/47)
 [Puppeteer PR](https://github.com/puppeteer/puppeteer/pull/6555)

**Comment by nzjony** [comment]
@drametoid , do you mean that you already tried this: https://github.com/heremaps/harp.gl/commit/c3c69692ab0fe76ac4c0c637a7979e6fbbbf0ff0 ?

**Comment by drametoid** [comment]
Hi @nzjony , thanks for the quick response. I tried the fix you've added but on primary analysis it doesn't seem to work - I'm still getting the error when it tries to install the **puppeteer** package (see previously mentioned error logs). When I set the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` env variable as mentioned in the error, it is able to compile successfully. 

Is there any chance you can try this on your machine? I'm using `CNTLM` for proxy authentication which listens on port 3128 but insecure (http).

**Comment by drametoid** [comment]
Could you also look at this PR [for puppeteer](https://github.com/puppeteer/puppeteer/pull/6555), might help. @nzjony

**Comment by nzjony** [comment]
@drametoid , very cool. Can you please create a PR with the fix? Glad you got it working

**Comment by drametoid** [comment]
@nzjony - Added #2212 
Thanks for pointing in the right direction. Cheers! 🍻
