### ISSUE TITLE
harp.gl should support rate limiting and not just return blank tiles

### ISSUE THREAD

**Issue by harrycollin** [heremaps/harp.gl#2222]
When looking at the horizon & or moving the camera quite fast I get 100s of errors like that below. Parts of the map stop loading and there are chunks left empty. This never used to be a problem in earlier versions (0.21.1) for example.

![image](https://user-images.githubusercontent.com/10602138/122549819-d115c200-d02a-11eb-8de8-e587b94e49ad.png)

Steps to reproduce: 
1. Download & extract zip
2. Run 'yarn' 
3. Enter your API key on Line 29 in 'pages/index.tsx'
4. Run 'yarn run dev'
5. Look at the horizon & move the camera around

I'd expect the tiles to load slower but not at the rate where your API is refusing requests.

![image](https://user-images.githubusercontent.com/10602138/122550880-27373500-d02c-11eb-8e6d-076b67f616da.png)

 - OS: Window 10
 - Browser Chrome
 - Version 91.0.4472.106

Example: [harp-bug.zip](https://github.com/heremaps/harp.gl/files/6676566/harp-bug.zip)

**Comment by nzjony** [comment]
@harrycollin , thanks for the bug ticket.

I guess you are on the freemium account? Do you have many users using this particular key? I notice you put it in the screenshot, it means that other people can use and also potentially misuse.

Have you looked in your account to see if there are any further details.

Unfortunately, if you get a 429, there isn't much we can do on our side, as the service is causing the issue.

Hope that helps,

**Comment by harrycollin** [comment]
@nzjony thanks for the reply. This is a new API key that I made specifically just for this project. I don't this this is misuse, but I'll check anyway

**Comment by nzjony** [comment]
@harrycollin , ok, weird. Try to create a new API key and let me know if that makes any difference?

There could be some problem locally, but I somewhat doubt it.

Do you have a globe projection with custom far plane? Potentially you are downloading too many tiles and the server returns the 429, but I somewhat doubt it.

**Comment by harrycollin** [comment]
@nzjony I made a new API key and still have the same problem. I don't have any exotic setup, just flat projection & MapControls controlling the camera. I could try making a new account to & generate a new API key that way but I don't see why it would make a difference.

**Comment by harrycollin** [comment]
Did you manage to test the project I attached?

**Comment by nzjony** [comment]
@harrycollin , thanks for trying a new API key. Ok, weird. 

Can you check in your developer network tab and see what value is given for: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After ?

I will try to test the product you have attached and get back to you.

**Comment by harrycollin** [comment]
@nzjony It's 10 
![image](https://user-images.githubusercontent.com/10602138/122925857-26b9d980-d35f-11eb-8271-c28e73142d8e.png)

**Comment by nzjony** [comment]
@harrycollin , I didn't get 429, but it does download many tiles.

See:
https://user-images.githubusercontent.com/2533428/122927829-8b7a3180-d369-11eb-9038-60371b8a24ce.mp4

Can you try reseting your router to get a new IP address?

**Comment by nzjony** [comment]
@harrycollin , can you try looking in your account to see if you have run out of the free amount of requests?

**Comment by harrycollin** [comment]
> @harrycollin , I didn't get 429, but it does download many tiles.
> 
> See:
> https://user-images.githubusercontent.com/2533428/122927829-8b7a3180-d369-11eb-9038-60371b8a24ce.mp4
> 
> Can you try reseting your router to get a new IP address?

My public IP address won't get changed unfortunately.

**Comment by harrycollin** [comment]
Btw, you can also check an online demo here: https://cassini-hackathon-parametricos.vercel.app/ 
I participated in a hackathon over the weekend with my company. This is what we put together.

**Comment by harrycollin** [comment]
> @harrycollin , can you try looking in your account to see if you have run out of the free amount of requests?
We're well within our limits: 
![image](https://user-images.githubusercontent.com/10602138/122929563-01c76580-d363-11eb-9884-a99bf0b8e6e1.png)

**Comment by nzjony** [comment]
@harrycollin , I get a 429 on that link.

Something weird is going on...

**Comment by nzjony** [comment]
Ahhh now it works....

**Comment by harrycollin** [comment]
Yep something weird indeed.

**Comment by nzjony** [comment]
@harrycollin , I wrote to you on slack.

**Comment by pakore** [comment]
The rate limit from Fermium accounts is 100 requests within 10 seconds, as it says in the headers you posted. This should be enough for panning. @nzjony for tilted maps this could be a problem since many tiles are requested at the same time.

**Comment by nzjony** [comment]
@pakore , thank you!!

Ok, that explains it @harrycollin.

You can then:
- upgrade to a paid account
- try specifying a different value for: https://www.harp.gl/docs/master/doc/interfaces/harp_mapview.datasourceoptions-1.html#storageleveloffset when creating the DataSource, this will request lower detail tiles (i.e. you will request less tiles), but the map will look worse.
- You could try enabling: https://www.harp.gl/docs/master/doc/interfaces/harp_mapview.mapviewoptions-1.html#enablemixedlod (but I'm not 100% sure that this works in flat projections).
- Wait for us to implement HARP-15979 (support rate limiting in harp.gl)

**Comment by nzjony** [comment]
@harrycollin , because the rate limiting issue is clear, I have changed the title to reflect the fact that harp.gl doesn't work with rate limiting.

However we are quite full at the moment working on internal tickets, so it may take some time to work on this, but I hope we can prioritise it, because it will also affect our paying customers.

**Comment by harrycollin** [comment]
That's fine. At least we found the source of of the issue. Thank you for investigating :)
