### ISSUE TITLE
Harp.gl styles that are mentioned on the here developer site, where are they?

### ISSUE THREAD

**Issue by sirakc** [heremaps/harp.gl#2231]
alright, take a look at these pictures,
![image](https://user-images.githubusercontent.com/57570123/124358426-dafc0f80-dc3d-11eb-8bbf-ff0f6ee0fd14.png)
![image](https://user-images.githubusercontent.com/57570123/124358431-e18a8700-dc3d-11eb-9149-71fd3fbd78d3.png)
![image](https://user-images.githubusercontent.com/57570123/124358437-e5b6a480-dc3d-11eb-81a8-fa8206d285e7.png)

these look AMAZING! I wish these were available for download as json because they seem to be custom made down to what color is used.  yea there are the "outline" and "streets"  style but are there downloadble styles? specially the ones I mentioned because I feel in love with the looks and I wish to go with something like that for my professional project

**Comment by nzjony** [comment]
hi @sirakc , thanks for you for the issue.

The top left image shows data which isn't currently consumable via some service, and the one below it is terrain, which also isn't currently public.

The bottom red theme is available here: https://github.com/heremaps/harp.gl/issues/1970#issuecomment-728981775

Does that help? Or do you need anything more?

**Comment by nzjony** [comment]
@sirakc , there is also a cool tool: https://heremaps.github.io/harp-map-editor/

Which can help you style the map.
