### ISSUE TITLE
When I set the receive shadow to true, the extruded polygon in the scene will dynamically appear a black background 

### ISSUE THREAD

**Issue by datouzhan** [heremaps/harp.gl#2247]
**Is your feature request related to a problem? Please describe.**
When I set the receive shadow to true, when I move the scene, the stretched polygon in the scene will dynamically appear a black background on the side of the stretched polygon with its back to the sun.

![1](https://user-images.githubusercontent.com/20176393/126962533-9210ee8c-8393-452a-a39d-ef7e6008938f.gif)

**Comment by nzjony** [comment]
@datouzhan , what lights do you have in the scene?

**Comment by datouzhan** [comment]
I set up AmbientLight and directionLight
![image](https://user-images.githubusercontent.com/20176393/127083990-2bce2d1a-4cef-47e8-9302-2383821c109c.png)

**Comment by datouzhan** [comment]
There is another problem. I use lambert material on the top of the building, but unfortunately it doesn't appear in the color I set. Instead, it appears as black. I want to set the material to accept the light and let him bainhua with the light.

**Comment by nzjony** [comment]
@datouzhan , sorry that I never responded. Somehow I lost track of this.

Have you made any progress?

I find it strange that you get this, we don't have such an issue on the shadow demo: https://www.harp.gl/docs/master/examples/#real-time-shadows.html

Have you done anything that could have affected it?
