### ISSUE TITLE
Load building height data from different sources and combining with Here Maps (ex. Open Street Maps - OSM)

### ISSUE THREAD

**Issue by messiosmarios** [heremaps/harp.gl#2270]
Hey awesome team! We've developed [CityLite](https://github.com/Parametricos/CityLite) using harp.gl and although you have the best data source, in our case for Cyprus, there are no building height data, and our users need them to load models on CityLite and have the surroundings in 3D.

I started to look elsewhere for possible data sources to stream, and I saw that Open Street Maps have these height data. 
Is there a way to stream and combine these data sources with yours?

Thanks, guys!

**Comment by nzjony** [comment]
@messiosmarios, see: https://github.com/heremaps/harp.gl/blob/c7f303ed8e95591db61dde30cad25f4303e65e3c/%40here/harp-vectortile-datasource/lib/OmvRestClient.ts#L71

We have some web service which gives OSM tiles. But we haven't tried this in a long time.

You need to make sure you have the correct URL & access_token. So, it is possible, but you will need to play around with it.
