### ISSUE TITLE
MapView: Failed to connect to geojson: Error during worker initialization

### ISSUE THREAD

**Issue by belopot** [heremaps/harp.gl#2278]
Hi,

I got the issue GeoJsonDataSource doesn't connect to mapView.
I'm using harp.gl - 0.26.0 and react app.
My code to add geoJson is following as:

![image](https://user-images.githubusercontent.com/46432435/129468842-4577d54c-3f24-4c59-90f2-3efa8e7dc371.png)

        
This is the error         
![image](https://user-images.githubusercontent.com/46432435/129468806-79d3d8e4-e048-4409-9a48-2a2508930c43.png)

Please let me know how to fix the issue

Thank you

**Comment by nzjony** [comment]
@belopot , thanks for the issue. 

Can you please share your geoJson so I can try locally?

**Comment by belopot** [comment]
Thank you. Here you go
https://drive.google.com/file/d/1apQRPO1DFMB4dx4ewC7haVT-4EdFJRA8/view?usp=sharing

**Comment by belopot** [comment]
I shared the project (React app)
https://drive.google.com/file/d/1hGWuuXxXfaMOHHebvflBXFqFAqEPAT9g/view?usp=sharing

**Comment by nzjony** [comment]
<img width="1080" alt="Screenshot 2021-08-16 at 12 35 05" src="https://user-images.githubusercontent.com/2533428/129551419-399a76d6-ad33-433a-9b83-b1832c1378ca.png">

This seems to be the problem... however you have explicitly set the decoder, so I don't know why it is requesting the `decoder.bundle.js`, will take a further look.

Consider to look at: https://github.com/slaylines/harp.gl-react-example in the mean time.

**Comment by nzjony** [comment]
Hmm, your GeoJsonDataProvider seems to need the web worker, because it needs to tile the geojson, see: https://github.com/heremaps/harp.gl/blob/79554faa5d650357068c951e022f386314e38de7/@here/harp-vectortile-datasource/lib/GeoJsonDataProvider.ts#L65

Which explains why it tries to request the `decoder.bundle.js`, see the other react harp.gl app.

**Comment by belopot** [comment]
Thank you @nzjony 

This issue was resolved by the harp.gl-react-example

**Comment by nzjony** [comment]
Ok, I'll close this issue then, but feel free to open it again if you need to.
