### ISSUE TITLE
Maintaining "North up" in Spherical Map

### ISSUE THREAD

**Issue by chrisdalke** [heremaps/harp.gl#2316]
Hi,
Is there any way to set the map controls to maintain "north up" or a specific camera Z rotation while dragging to orbit the spherical map? I would like to have more control over the direction of the globe, or at least to reset the orientation at the end of every drag motion.

The fundamental issue that I am trying to avoid is that if a user drags slightly off-axis, the Z rotation of the camera will slowly accumulate. Dragging around the earth in a series of smaller motions eventually causes the map to turn upside down, which is disorienting because it doesn't match a user's intent.

Other 3d map renderers handle this in a number of ways:
- Google maps locks north to always be up
- CesiumJS defaults to north up, allowing the user to rotate the orientation, but maintains that orientation. If the user hits the north/south pole, the orientation is reset.

**Comment by brent-williams** [comment]
@chrisdalke if you can harp.gl yourself you can add the following to the bottom of MapControls.mouseMove(), just above `this.updateMapView`:

```ts
        MapViewUtils.setRotation(this.mapView, THREE.MathUtils.radToDeg(0), THREE.MathUtils.radToDeg(0))
```

If you're not building harp.gl (or not using MapControls) you can add an event listener on MapView for `MapViewEventNames.CameraPositionChanged` and reset the camera there.

Neither of the above solutions are that great though, as both will give the occasional rendered frame with the camera rotated before the correction kicks in.  @nzjony am looking forward to HARP-12051 as well.
