### ISSUE TITLE
Drawing exception problem

### ISSUE THREAD

**Issue by zengguilin** [heremaps/harp.gl#2352]
![image](https://user-images.githubusercontent.com/39285833/148318022-af569023-17e3-4dea-bc10-ab0e52e03942.png)

**Comment by zengguilin** [comment]
![image](https://user-images.githubusercontent.com/39285833/148318133-83f9bef3-e754-4e44-b627-3416a6cf1f24.png)
![image](https://user-images.githubusercontent.com/39285833/148318145-495d605c-93f7-46e2-b44f-d926ed969365.png)

**Comment by zengguilin** [comment]
![image](https://user-images.githubusercontent.com/39285833/148320924-60ee77c4-58b4-44df-8234-ffd4f8cdd5ce.png)

**Comment by nzjony** [comment]
Thanks @zengguilin

Thanks for reporting, the issue was reported already: https://github.com/heremaps/harp.gl/issues/1460 but we never fixed it.
