### ISSUE TITLE
[feature] time-based tools

### ISSUE THREAD

**Issue by trusktr** [heremaps/harp.gl#2357]
**Is your feature request related to a problem? Please describe.**

Hello again! :)  Cesium has time-based tools for showing global data based on date times. Has anyone made any tooling like this for Harp.gl yet?

**Describe the solution you'd like**

For example, in Cesium we can add the built-in timeline UI, drag the slider, and this will change the daylight/shadow direction as well as the stars orientation in the background.

This can be useful for showing certain data on the globe based on a specific time or time range.

**Describe alternatives you've considered**

Implementing from scratch

**Comment by nzjony** [comment]
hi @trusktr , nice to hear from you again.

I'm only working on this project indirectly (i.e. the product I work on uses it), so my help can be limited, however there are two examples that may help: https://www.harp.gl/docs/master/examples/#datasource_features_polygons.html and https://www.harp.gl/docs/master/examples/#real-time-shadows.html (can show the shadows at a given time of day).

But other than that, I don't know of anything related to time based visualisations in harp.

**Comment by trusktr** [comment]
Thanks. Indeed I saw the time-bases shadows example. That's a good starting point. Will need to make custom timeline UI (f.e. for scrubbing the time, setting time range, etc, similar to Cesium)
