### ISSUE TITLE
Equirectangular Tiles supported?

### ISSUE THREAD

**Issue by pwambach** [heremaps/harp.gl#2361]
Hey!
Is it possible to display equirectangular raster tiles with harp.gl, i.e. tiles where there are two quadratic tiles on level 0?
I saw harp.gl supports equirectangular projection and various tiling schemes but wasn't able to produce a working example.
Thanks in advance!

**Comment by nzjony** [comment]
@pwambach , Yes, we have an equirectangular projection.

See: https://github.com/heremaps/harp.gl/blob/d7e7b6718c0c69f790102d3f544998b51db7d647/@here/harp-geoutils/lib/tiling/HereTilingScheme.ts#L17

And specifically the `subdivisionScheme`, does that suit you. If not, you can create your own class which implements the SubdivisionScheme scheme, and pass it to the MapView.

**Comment by pwambach** [comment]
Thanks for your fast answer!

Do I have to create my own DataSource class to use a different tiling scheme? I tried with a little debug example using the WebTileDataSource and it doesn't seem to have any effect.

Here is my example: https://jsfiddle.net/xeucz93d
