### ISSUE TITLE
Docs and online examples is 404

### ISSUE THREAD

**Issue by maqingbo** [heremaps/harp.gl#2394]
When I open the docs as usual, it's no longer accessible, same as the online examples.

- https://www.harp.gl/

<img width="729" alt="harp" src="https://user-images.githubusercontent.com/20136852/180120462-47246f00-9165-4b1b-a743-de0c513020df.png">

- http://harp.gl.s3-website-us-east-1.amazonaws.com/

<img width="721" alt="harp-02" src="https://user-images.githubusercontent.com/20136852/180120422-8631469f-2bb5-4842-b755-ee0640a38e3c.png">

What I want to know is, is there some glitch or is it that these two addresses are no longer maintained?

By the way, I'm in China, and I've ruled out the reason that it's not the network.

**Comment by nzjony** [comment]
The website has been taken down :(

**Comment by maqingbo** [comment]
It is bad news :(

Harp.gl is a great library, we are trying to use it for some urban GIS analysis work and have achieved some good results. Thanks to those who have contributed, hope it will be updated again someday.

In case someone will use the docs and examples, I created a new github pages, the examples are already accessible, I will post the docs page later.

- https://maqingbo.github.io/harp.gl-examples/#getting-started_hello-world_js-bundle.html

Docs is ok now.

- https://maqingbo.github.io/harp.gl-docs/

**Comment by nzjony** [comment]
Thanks @maqingbo , yes it is sad.

Great to see you use it, all the best! I look forward to see what you get up to with it, please let me know.
