### ISSUE TITLE
Update @here/generator-harp.gl npm package to fix mismatched map div ids in CSS and HTML

### ISSUE THREAD

**Issue by dbabbs** [heremaps/harp.gl#444]
Just ran through the [getting started instructions](https://github.com/heremaps/harp.gl/blob/master/docs/GettingStartedGuide.md) and used the `npx -p yo -p @here/generator-harp.gl yo @here/harp.gl` generator.

In `index.html`, the map `id`s do not match.
The CSS uses `mapCanvas`:
```
#mapCanvas {
   position: absolute;
   border: 0px;
   left: 0px;
   width: 100%;
   height: 100%;
   overflow: hidden;
    z-index: -1
}
```
while the html uses `map`:
```
<canvas id="map"></canvas>
```

This causes a map that is approximately 2x the size of the screen that is cut off. Since the `body` and `map` both have `overflow: none`, it is not clear what is going on, there is somewhat pixelated map and labels.

This repository's ` @here/generator-harp.gl` appears to be updated with matching `id`s for the map: [see file](https://github.com/heremaps/harp.gl/blob/master/%40here/generator-harp.gl/generators/app/templates/index.html)

I assume the npm packages need to be updated?

**Comment by ninok** [comment]
This was already fixed with this PR: https://github.com/heremaps/harp.gl/pull/405
It will be part of the next release.

**Comment by dbabbs** [comment]
👏
