### ISSUE TITLE
Near plane too far in globe demo.

### ISSUE THREAD

**Issue by nzjony** [heremaps/harp.gl#587]
Reported here: https://twitter.com/CihadTurhan/status/1142507682500419586

![D9sArZhW4AAX0IR](https://user-images.githubusercontent.com/2533428/60114200-a3ffe300-9773-11e9-9162-5909dd59f879.jpeg)

Internal link: HARP-6295

**Comment by nzjony** [comment]
Should be fixed by internal ticket: HARP-6274 (Touch controls for globe) which is currently in progress.

**Comment by Astrak** [comment]
Fixed in #616
