### ISSUE TITLE
Clicking on the links in the README.md in harp-examples gives 403

### ISSUE THREAD

**Issue by nzjony** [heremaps/harp.gl#588]
Go to: http://harp.gl.s3-website-us-east-1.amazonaws.com/docs/master/doc/modules/harp_examples.html

Click on: "Camera with free movement", which links to: http://harp.gl.s3-website-us-east-1.amazonaws.com/docs/master/doc/modules/src/camera_free.ts

This gives a 403 forbidden.

Reported here: https://twitter.com/timothyjmartin/status/1143139074938683393?s=20

Internal: HARP-5701

**Comment by nzjony** [comment]
I took a look at scripts/doc-snippets.ts, one idea could be to do a similar thing for mentions of source files, use a regex to find the mentioned .ts files, and then copy those across that are actually mentioned.

The second benefit would also to find any links which are dead.

**Comment by Astrak** [comment]
Fixed that in the readme but not in the doc

**Comment by ninok** [comment]
This only affects the Readme rendered via Typedoc. If you open the readme in github directly it works:
https://github.com/heremaps/harp.gl/blob/master/%40here/harp-examples/README.md

**Comment by ninok** [comment]
Maybe https://www.npmjs.com/package/typedoc-plugin-linkrewriter could be an option to point the links in the Typedoc version of README.md to th elatest source files on github.
