### ISSUE TITLE
Strange clouds in satellite imagery

### ISSUE THREAD

**Issue by dbabbs** [heremaps/harp.gl#673]
![Screen Shot 2019-07-30 at 4 37 12 PM](https://user-images.githubusercontent.com/221746/62256251-6a934680-b3b5-11e9-9300-418041104b63.png)

Reported by Tomas Gerlich (Internal/Berkeley)

These are not clouds in the satellite imagery.

Might be due to lighting in theme file?

**Comment by Astrak** [comment]
I wonder if this is not the z fighting of the background datasource? The fix was merged on Monday. Does it still happen on master?

**Comment by zbigg** [comment]
Confirmed, this is fixed in master by  #658.
