### ISSUE TITLE
GeoJSON Point and LineString features with same coordinates display slightly differently

### ISSUE THREAD

**Issue by tomasberkeley** [heremaps/harp.gl#699]
![Screen Shot 2019-08-07 at 4 30 28 PM](https://user-images.githubusercontent.com/53882996/62665780-4e535480-b935-11e9-880d-a92d771f3aa3.png)

In the picture both the red dots and the green lines share the same exact coordinates however the red dots do not appear exactly on top of the line and exhibit a somewhat "wobbly" behavior.

**Comment by Astrak** [comment]
Hello Tomas, thank you for your report. 

Can you detail your setup? How are you visualizing your GeoJson? What datasource + dataprovider do you pass it through?

**Comment by tomasberkeley** [comment]
Hi Adrien,

I am using GeoJsonDataProvider(name, url) and OmvDataSource to create the datasource. I then add it to a MapView using a simple style sheet where I assign color with 
"technique": "circles" and with "technique": "solid-line" when "$geometryType == 'point'" and "$geometryType == 'line'", respectively.

To create the GeoJSON file I have a sequence of coordinates which I insert as "type": "LineString" to the file (these would be the green lines). To visualize the exact end-points of each line segment I also insert the same exact coordinates that formed the LineString, but insert them each separately as "type": "Point" (these are the red dots). I would expect the red dots to line up precisely on top of the green lines without the "wobbly" effect since both features share the same exact coordinates.

Thank you for looking into it!

Tomas

**Comment by ninok** [comment]
Hi Michael,

I guess the basic setup is similar to the one of our geojson example:

- https://www.harp.gl/docs/master/examples/#datasource_geojson_chloropleth.html
- https://github.com/heremaps/harp.gl/blob/master/%40here/harp-examples/src/datasource_geojson_chloropleth.ts

The only thing you have to change are the geojson file and the styleset as described by Tomas.

Best regards,
Nino

**Comment by nzjony** [comment]
It should be tested after #801  is merged to see if this is a fix.

**Comment by nzjony** [comment]
I managed to reproduce with the following geojson.

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.383072316646576,
          52.53059023621278
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.383429050445555,
          52.53068487407586
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.383855521678925,
          52.53079419687071
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.384153246879578,
          52.53087414919016
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Point",
        "coordinates": [
          13.384518027305603,
          52.5309867348626
        ]
      }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
             13.383072316646576,
          52.53059023621278
          ],
          [
            13.383429050445555,
          52.53068487407586
          ],
          [13.383855521678925,
          52.53079419687071],
          [ 13.384153246879578,
          52.53087414919016],
          [13.384518027305603,
          52.5309867348626]
        ]
      }
    }
  ]
}

**Comment by nzjony** [comment]
@amsXYZ tested it, but it is unfortunately not related to #801

**Comment by mkalygin** [comment]
@ninok I've prepared the demo with reproduction of this issue.

I couldn't make it look way off the line like on the reporter's screenshot, but there is a small discrepancy in point vs line coordinates. And I think it's related to the original bug.

To take a look at the demo:
1. Get `HARP-6762-repro` branch from my fork:  https://github.com/mkalygin/harp.gl/tree/HARP-6762-repro
2. `yarn start`
3. Navigate to http://localhost:8080/#datasource_features_lines-and-points.html

You can see my changes here:
https://github.com/mkalygin/harp.gl/commit/8a77a7fc28fcd8c84b617495816e14271b740e38

Screenshot:
![image](https://user-images.githubusercontent.com/1662910/66753169-de64cb80-ee9b-11e9-8b56-a0b366b3505b.png)
