### ISSUE TITLE
There are two black holes in the Antarctic and the North Pole.

### ISSUE THREAD

**Issue by songsgroup** [heremaps/harp.gl#704]
**Describe the bug**
There are two black holes in the Antarctic and the North Pole.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nzjony** [comment]
Thanks @songsgroup for your issue.
This will be fixed by: https://github.com/heremaps/harp.gl/pull/653

**Comment by nzjony** [comment]
This should be fixed, please check: https://www.harp.gl/docs/master/examples/#getting-started_globe-projection.html
