### ISSUE TITLE
3D  mode can change the angle of view

### ISSUE THREAD

**Issue by songsgroup** [heremaps/harp.gl#705]
**Is your feature request related to a problem? Please describe.**
3D Earth mode can change the angle of view

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by nzjony** [comment]
hi @songsgroup , I don't quite understand the issue? Are you meaning that you can't tilt in globe?

**Comment by okanishchev** [comment]
I think, it's about not constant __up__ vector of camera, so you can see south pole _above_ north pole for example.
