### ISSUE TITLE
Instructions for adding local harp.gl modules into project

### ISSUE THREAD

**Issue by dbabbs** [heremaps/harp.gl#717]
I've come across a few people (including myself) asking about configuration instructions on how to use the harp.gl modules from the github source. This way one can use the most recent features committed to master, but not yet available in the npm packages. Can we add a quick guide in this repository on how to do this?

cc @tomasberkeley

**Comment by ninok** [comment]
I did this once in my personal project:
https://github.com/ninok/harp-physics/commit/04d3b8db9e4c69319695a97d352420472020b4f9

For sure this deserves a separate section in the getting started guide. I created an internal ticket as well.

**Comment by dbabbs** [comment]
+1
