### ISSUE TITLE
Android SDK

### ISSUE THREAD

**Issue by shakesgar** [heremaps/harp.gl#790]
Hi Guys,

How can I add a custom map to an android project?

Is there an SDK or is only a WebView supported now?

Would really love to replace my google 3D maps with this?

Thank you.

**Comment by shakesgar** [comment]
Hi, Thanks for the email. I'll take a look at integrating with react native and let you know if any problems.

Thanks again

**Comment by dbabbs** [comment]
HERE also does offer native [mobile SDKs](https://developer.here.com/develop/mobile-sdks) for both iOS and Android. Although they do not have as many advanced 3D capabilities as harp.gl, they do offer basic 3D functionality like 3D buildings and camera tilt.
