### ISSUE TITLE
3D city models & landmarks data

### ISSUE THREAD

**Issue by jamesdeantv** [heremaps/harp.gl#896]
Where can I find HERE's advanced city models data? I am specifically interested in the textured buildings asset.

Is it available for public consumption?

![coming-soon](https://user-images.githubusercontent.com/16325635/66657446-d98ae800-ec0d-11e9-9f55-85a37088fb36.png)

**Comment by musculman** [comment]
Hi @jamesdeantv !
That data is available to be used on [HERE's Open Location Platform](https://developer.here.com/products/open-location-platform). I recommend you take a look at those materials, on the getting started you should find a link to request a free trial.

On harp.gl side we are working on providing the capabilities to render all of these datasets, but not on the data offer. We plan to add some open sourced examples showcasing these features, but we are still working out the exact details. Stay tuned for that for the first months of 2020!
