### ISSUE TITLE
Can't see labels and street roads names 

### ISSUE THREAD

**Issue by ATMEGA17** [heremaps/harp.gl#957]
When using the theme mentioned in this example 
https://www.harp.gl/docs/master/examples/#rendering_post-effects_themes.html

both themes doesn't display labels 
and also i see this WebGL error on the console

![image](https://user-images.githubusercontent.com/16512879/67626885-b2f1c180-f849-11e9-9475-b4dd13df9d3e.png)

is there a  way to display labels on this theme

**Comment by Astrak** [comment]
You can go at the 'open sourced themes' example and select the theme you're looking for, labels are enabled in this one. In the 'post effects' example, `map.renderLabels` is set to false, you can set it to true locally if you also want to see labels there.

**Comment by ATMEGA17** [comment]
Thank you @Astrak for your reply 

but as you can see in the image below RenderLabels is already true even after resetting it to true still the street labels are not visible
![image](https://user-images.githubusercontent.com/16512879/67627416-01a45900-f854-11e9-8323-a7ccfc6fd2f6.png)

and for open sourced theme example i didn't find it if you may send me the link  

thank you

**Comment by ATMEGA17** [comment]
https://www.harp.gl/docs/master/examples/#getting-started_open-sourced-themes.html
the labels in day theme are good
![image](https://user-images.githubusercontent.com/16512879/67627526-af643780-f855-11e9-83aa-c42120b066bc.png)

But when changing the theme to street or any thing else 

nothing is visible

![image](https://user-images.githubusercontent.com/16512879/67627529-ce62c980-f855-11e9-9360-4074d6e9aa3a.png)

**Comment by Astrak** [comment]
My mistake, these themes do not render labels. You can do so by modifying them, as labelling is defined in the theme. You can copy another theme with the labels you like for instance.
